import {all,one,put,putMany,remove,logEvent} from './db.js';
import {FAMILIES,STATUSES,BADGES,CHECKLISTS,LEAD_TASKS,esc,clean,validTool,normalizeTool,badgeValue,isComplete,photo,quarterOf} from './schema.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let tools=[],page='operations',section='live',filterQuarter=quarterOf(),query='',editor=null,editorTab='info',presentation=false,slideIndex=0,pendingImport=null,saveBusy=false;
const nav=[['operations','OPERATIONS CENTER'],['tools','TOOLS CENTER'],['shipping','SHIPPING CENTER'],['priorities','PRIORITY CENTER'],['status','STATUS CENTER'],['quarter','QUARTER SUMMARY'],['search','SEARCH CENTER'],['administration','ADMINISTRATION']];
function notify(message,error=false){$('#footerMessage').textContent=message;const t=$('#toast');t.textContent=message;t.style.background=error?'#75283b':'#1c5a7c';t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),5000)}
async function refresh(){tools=(await all('tools')).filter(validTool).map(normalizeTool).sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true}));render()}
const current=()=>tools.filter(t=>t.quarter===filterQuarter||t.originalQuarter===filterQuarter);
const stats=arr=>({total:arr.length,waiting:arr.filter(t=>['OI','Waiting for FI'].includes(t.toolStatus)).length,fi:arr.filter(t=>['FI','Engineering','Powered Down'].includes(t.toolStatus)).length,packing:arr.filter(t=>t.toolStatus==='Packing').length,shipped:arr.filter(t=>t.toolStatus==='Shipped').length});
function counts(arr){const s=stats(arr);return `<div class="stats">${[['ALL TOOLS',s.total],['WAITING FOR FI',s.waiting],['IN FI',s.fi],['PACKING',s.packing],['SHIPPED',s.shipped]].map(([label,v])=>`<div class="stat"><b>${v}</b><small>${label}</small></div>`).join('')}</div>`}
function top(){const s=stats(current());$('#headerTitle').textContent=nav.find(n=>n[0]===page)?.[1]+' — '+filterQuarter;$('#globalNav').innerHTML=nav.map(([id,name])=>`<button data-page="${id}" class="${page===id?'active':''}">${name}</button>`).join('');$('#globalStatus').innerHTML=`<div class="status-line"><strong>LEADS ALERT</strong><span>${s.fi} in FI · ${s.packing} packing · ${s.waiting} waiting for FI</span></div><div class="status-line"><strong>SYSTEM STATUS</strong><span>${s.total} verified local tool records · ${s.shipped} shipped in ${esc(filterQuarter)}</span></div><div class="status-line warn"><strong>COMMAND CENTER</strong><span>V12 FOUNDATION TEST · Local IndexedDB only · Microsoft List is NOT connected · Import verified records before use</span></div>`;const quarters=[...new Set([quarterOf(),...tools.map(t=>t.quarter),...tools.map(t=>t.originalQuarter)].filter(Boolean))].sort();$('#pageNav').innerHTML=`<button data-section="live" class="${section==='live'?'active':''}">LIVE OPERATIONS</button><button data-section="daily" class="${section==='daily'?'active':''}">DAILY STATUS</button><button data-section="summary" class="${section==='summary'?'active':''}">SUMMARY</button><button data-action="add">+ ADD TOOL</button><button data-action="export">BACKUP JSON</button><button data-action="import">IMPORT BACKUP</button><select id="quarterSelect" aria-label="Quarter" class="search" style="width:auto">${quarters.map(q=>`<option value="${esc(q)}" ${q===filterQuarter?'selected':''}>${esc(q)}</option>`).join('')}</select>`}
function head(title,buttons=''){return `<div class="page-head"><h1>${esc(title)}</h1><div class="toolbar">${buttons}</div></div>`}
function kv(label,value){return `<div class="pair"><small>${esc(label)}</small><strong>${esc(value||'—')}</strong></div>`}
function progress(t){const states=Object.values(t.fiChecklistStates||{});return states.length?Math.round(states.filter(isComplete).length/states.length*100):0}
function card(t){const b=BADGES.map(name=>{const v=badgeValue(t,name);return `<div class="badge ${isComplete(v)?'done':/^(no|not|need|missing|unassigned)/i.test(v)?'todo':''}"><button data-badge="${esc(t.id)}" data-name="${esc(name)}" title="Edit badge">${esc(name)}<br>${esc(v)}</button></div>`}).join('');const pct=progress(t);return `<article class="tool-card"><div class="tool-top"><h2>${esc(t.id)} · ${esc(t.codename)}</h2><button data-edit="${esc(t.id)}">EDIT TOOL</button></div><div class="tool-grid"><div class="tool-col"><img class="tool-photo" src="${photo(t)}" alt="${esc(t.codename)} tool"><div>${kv('UTID',t.id)}${kv('Model',t.model)}${kv('Customer',t.customer)}${kv('Sales Order',t.salesOrder)}${kv('Driver',t.driver)}${kv('Ship Date',t.shipDate)}</div></div><div class="tool-col">${kv('FI Process Status',t.toolStatus)}${kv('Current Checklist',t.currentChecklist)}${kv('Micro Schedule',t.microSchedule)}${kv('FI Forecast',t.fiForecast)}${kv('Latest Status',t.latestStatus)}<div>${kv('FI Checklists',pct+'%')}<div class="bar"><span style="width:${pct}%"></span></div></div><button data-checklist="${esc(t.id)}">EDIT CHECKLISTS</button></div><div class="tool-col">${kv('Quarter',t.quarter)}${kv('Priority',t.priority||'Unassigned')}<div class="badge-grid">${b}</div></div></div></article>`}
function listTools(arr){return arr.length?`<div class="tools">${arr.map(card).join('')}</div>`:'<div class="panel"><p>No verified tools in this view.</p><p class="hint">Use ADD TOOL to create a record or IMPORT BACKUP to load an existing verified dataset. No records are automatically copied from older browser storage.</p></div>'}
function operations(){let a=current().filter(t=>t.toolStatus!=='Archived');if(section==='daily')return head('Daily Status')+counts(a)+`<div class="panel"><table class="data-table"><thead><tr><th>UTID</th><th>Tool</th><th>Status</th><th>Latest update</th><th>Edit</th></tr></thead><tbody>${a.map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(t.codename)}</td><td>${esc(t.toolStatus)}</td><td>${esc(t.latestStatus)}</td><td><button data-edit="${esc(t.id)}">EDIT</button></td></tr>`).join('')}</tbody></table></div>`;if(section==='summary')return quarterPage();return head('Live Operations',`<button data-action="present">PRESENTATION MODE</button>`)+counts(a)+listTools(a)}
function toolPage(){const a=current();return head('Tools Center')+counts(a)+listTools(a)}
function shippingPage(){const a=current().filter(t=>['FI','Engineering','Powered Down','Packing','Shipped'].includes(t.toolStatus));return head('Shipping Center')+`<div class="panel"><table class="data-table"><thead><tr><th>UTID</th><th>System</th><th>Status</th><th>Ship date</th><th>Actions</th></tr></thead><tbody>${a.map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(t.codename)}</td><td>${esc(t.toolStatus)}</td><td>${esc(t.shipDate)}</td><td><button data-edit="${esc(t.id)}">EDIT</button></td></tr>`).join('')}</tbody></table></div>`}
function prioritiesPage(){const a=current().filter(t=>t.toolStatus!=='Shipped'&&t.toolStatus!=='Archived').sort((a,b)=>(a.priority||999)-(b.priority||999));return head('System Priorities')+`<div class="panel"><table class="data-table"><thead><tr><th>Priority</th><th>UTID</th><th>Tool</th><th>Status</th><th>Driver</th><th>Action</th></tr></thead><tbody>${a.map(t=>`<tr><td>${esc(t.priority||'—')}</td><td>${esc(t.id)}</td><td>${esc(t.codename)}</td><td>${esc(t.toolStatus)}</td><td>${esc(t.driver)}</td><td><button data-edit="${esc(t.id)}">EDIT</button></td></tr>`).join('')}</tbody></table></div>`}
function quarterPage(){const a=current(),s=stats(a),groups=FAMILIES.filter(f=>a.some(t=>t.codename===f)).map(f=>{const ts=a.filter(t=>t.codename===f),n=ts.filter(t=>t.toolStatus==='Shipped').length;return `<div class="quarter-row"><strong>${esc(f)}</strong><div class="quarter-track"><span style="width:${ts.length?100*n/ts.length:0}%"></span></div><strong>${n} of ${ts.length}</strong></div>`}).join('');return head(filterQuarter+' Quarter Summary',`<button data-action="present">PRESENTATION MODE</button>`)+counts(a)+`<div class="panel"><h2>${s.shipped} of ${s.total} shipped</h2>${groups||'<p>No verified tools in this quarter.</p>'}</div>`}
function statusPage(){return head('Status Center')+`<div class="panel">${counts(current())}<p class="hint">All figures are calculated from verified local tool records. Activity, presence, and automatically generated A- identifiers are excluded.</p></div>`}
function searchPage(){const q=query.toLowerCase();const a=tools.filter(t=>[t.id,t.codename,t.model,t.customer,t.toolStatus,t.currentChecklist,t.latestStatus,t.driver,JSON.stringify(t.waferTracking||{}),JSON.stringify(t.badges||{})].some(v=>String(v||'').toLowerCase().includes(q)));return head('Search All Tools')+`<div class="panel"><label class="field">Search UTID, status, checklist, driver, wafers or badge<input id="searchInput" class="search" value="${esc(query)}" placeholder="e.g. FI_150, Reduced Process, Shiny"></label><div class="editor-actions"><button data-action="runsearch">SEARCH</button></div></div><p class="muted">${a.length} result(s) · Includes all quarters</p>${listTools(query?a:[])}`}
function adminPage(){return head('Administration / Data Safety')+`<div class="panel"><h2>V12 Local Recovery Database</h2><p>This foundation uses IndexedDB and stores each physical tool as an independent record. It does not modify Microsoft Lists or older V11 browser data.</p><div class="toolbar"><button data-action="export">EXPORT VERIFIED BACKUP</button><button data-action="import">IMPORT BACKUP</button><button data-action="diagnostics">DIAGNOSTICS</button></div><p class="hint">Keep V11 and V12 in separate folders. V12 does not migrate browser storage automatically. Import a trusted JSON backup and review the preview before committing.</p></div><div class="panel" style="margin-top:12px"><h2>Feature status</h2><table class="data-table"><tr><td>Tool CRUD / badges / FI and Lead tasks</td><td>Local IndexedDB — test required</td></tr><tr><td>Quarter views / priorities / shipping / search</td><td>Local verified records</td></tr><tr><td>Microsoft List multi-user sync</td><td class="error-text">NOT IMPLEMENTED IN V12 FOUNDATION</td></tr><tr><td>Advanced quarter archive / legacy meeting workflows</td><td class="error-text">NOT YET MIGRATED</td></tr></table></div>`}
function render(){top();$('#main').classList.remove('presentation');presentation=false;$('#main').innerHTML=({operations,tools:toolPage,shipping:shippingPage,priorities:prioritiesPage,status:statusPage,quarter:quarterPage,search:searchPage,administration:adminPage}[page]||operations)()}
function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');$('#modalBody').scrollTop=0}
function closeModal(){if(saveBusy)return;$('#modal').classList.add('hidden');editor=null}
const field=(key,label,value='',type='text')=>`<label class="field">${esc(label)}<input name="${esc(key)}" type="${type}" value="${esc(value)}" ${key==='id'&&editor?.existing?'readonly':''}></label>`;
const select=(key,label,value,values)=>`<label class="field">${esc(label)}<select name="${esc(key)}">${[...new Set([value,...values])].map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v||'—')}</option>`).join('')}</select></label>`;
function editorForm(){const t=editor.draft;const tabs=[['info','TOOL INFO'],['fi','FI PROGRESS'],['lead','LEAD / ADMIN'],['shipping','SHIPPING'],['wafers','SYSTEM WAFERS'],['badges','BADGES'],['notes','STATUS / NOTES']];const box=(x)=>`<div class="field-grid">${x}</div>`;let content='';if(editorTab==='info')content=box(field('id','UTID',t.id)+select('codename','Tool Type',t.codename,FAMILIES)+field('model','Model',t.model)+field('customer','Customer',t.customer)+field('salesOrder','Sales Order',t.salesOrder)+field('driver','Driver',t.driver)+field('quarter','Quarter',t.quarter)+field('originalQuarter','Original Quarter',t.originalQuarter)+field('priority','Priority',t.priority,'number'));
if(editorTab==='fi')content=box(select('toolStatus','Tool Status',t.toolStatus,STATUSES)+field('currentChecklist','Current FI Checklist',t.currentChecklist)+field('microSchedule','Micro Schedule Target',t.microSchedule)+field('fiForecast','FI Forecast',t.fiForecast))+`<p class="hint">FI checklist states can be edited in the checklist workspace.</p><button data-action="editchecklist">OPEN FI CHECKLIST</button>`;
if(editorTab==='lead')content=checkRows('lead',LEAD_TASKS,t.leadTasks||{});
if(editorTab==='shipping')content=box(field('shipDate','Ship Date',t.shipDate,'date')+select('toolStatus','Tool Status',t.toolStatus,STATUSES));
if(editorTab==='wafers')content=box(['shiny','haze','dsw65','dsw65f'].map(k=>field('wafer_'+k,'Additional '+k.toUpperCase(),t.waferTracking.additional[k]||0,'number')).join(''))+`<p class="hint">These are additional FI wafers, not the base system kit.</p>`;
if(editorTab==='badges')content=checkRows('badge',BADGES,Object.fromEntries(BADGES.map(n=>[n,badgeValue(t,n)])));
if(editorTab==='notes')content=`<div class="field-grid">${field('latestStatus','Latest System Status',t.latestStatus)}<label class="field">Lead Notes<textarea name="notes">${esc(t.notes)}</textarea></label></div>`;
modal((editor.existing?'EDIT TOOL · ':'ADD TOOL · ')+(t.id||'NEW'),`<div class="editor-layout"><div class="editor-nav">${tabs.map(([k,v])=>`<button class="${editorTab===k?'active':''}" data-tab="${k}">${v}</button>`).join('')}</div><div><form id="toolForm">${content}<div class="editor-actions"><button type="submit" class="good">SAVE TOOL</button><button type="button" data-action="cancel">CANCEL</button></div></form></div></div>`)}
function checkRows(kind,names,states){return `<div class="checklist">${names.map(name=>`<label class="check-row"><span>${esc(name)}</span><select data-${kind}-key="${esc(name)}">${[states[name]||'Not Started','Not Started','In Progress','Complete','Need Attention','Yes','No','Issued','Requested','Verified'].filter((x,i,a)=>a.indexOf(x)===i).map(v=>`<option value="${esc(v)}" ${v===(states[name]||'Not Started')?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`).join('')}</div>`}
function captureEditor(){if(!editor)return;const f=$('#toolForm');if(!f)return;for(const e of f.elements){if(!e.name)continue;if(e.name.startsWith('wafer_'))editor.draft.waferTracking.additional[e.name.slice(6)]=Math.max(0,Number(e.value)||0);else if(e.name==='priority')editor.draft.priority=Math.max(0,Number(e.value)||0);else editor.draft[e.name]=e.value}$$('[data-badge-key]').forEach(e=>editor.draft.badges[e.dataset.badgeKey]=e.value);$$('[data-lead-key]').forEach(e=>editor.draft.leadTasks[e.dataset.leadKey]=e.value)}
function openEditor(id){const existing=!!id;const t=existing?tools.find(x=>x.id===id):normalizeTool({id:'',codename:'Panamera',quarter:filterQuarter,originalQuarter:filterQuarter});if(!t){notify('Tool not found',true);return}editor={existing,draft:structuredClone(t)};editorTab='info';editorForm()}
async function saveTool(){if(saveBusy||!editor)return;captureEditor();const t=normalizeTool(editor.draft);if(!validTool(t)){notify('A real UTID and tool type are required',true);return}if(!editor.existing&&tools.some(x=>x.id===t.id)){notify('UTID already exists — open the existing tool instead',true);return}saveBusy=true;try{t.updatedAt=new Date().toISOString();await put('tools',t);await logEvent('SAVED TOOL '+t.id);saveBusy=false;closeModal();await refresh();notify('Saved and committed: '+t.id)}catch(e){saveBusy=false;notify('SAVE FAILED: '+e.message,true);console.error(e)}}
function openChecklist(id){const t=tools.find(x=>x.id===id);if(!t)return;const codes=[...new Set([...CHECKLISTS,...Object.keys(t.fiChecklistStates||{})])];modal('FI & LEAD CHECKLIST · '+t.id,`<form id="checkForm" data-id="${esc(id)}"><h3>FI CHECKLIST</h3>${checkRows('fi',codes,t.fiChecklistStates||{})}<h3>LEAD / ADMIN TASKS</h3>${checkRows('lead',LEAD_TASKS,t.leadTasks||{})}<div class="editor-actions"><button type="submit" class="good">SAVE CHECKLISTS</button><button type="button" data-action="close">CANCEL</button></div></form>`)}
async function saveChecklist(form){const t=tools.find(x=>x.id===form.dataset.id);if(!t)return;const n=structuredClone(t);form.querySelectorAll('[data-fi-key]').forEach(e=>n.fiChecklistStates[e.dataset.fiKey]=e.value);form.querySelectorAll('[data-lead-key]').forEach(e=>n.leadTasks[e.dataset.leadKey]=e.value);try{await put('tools',{...n,updatedAt:new Date().toISOString()});await logEvent('SAVED CHECKLIST '+n.id);closeModal();await refresh();notify('Checklists saved: '+n.id)}catch(e){notify('SAVE FAILED: '+e.message,true)}}
function openBadge(id,name){const t=tools.find(x=>x.id===id);if(!t)return;modal('BADGE · '+id,`<form id="badgeForm" data-id="${esc(id)}" data-name="${esc(name)}"><label class="field">${esc(name)}<input name="badge" value="${esc(badgeValue(t,name))}" required></label><p class="hint">Enter the operational state. It is stored with this tool and shown on every card.</p><div class="editor-actions"><button type="submit" class="good">SAVE BADGE</button><button type="button" data-action="close">CANCEL</button></div></form>`)}
async function saveBadge(f){const t=tools.find(x=>x.id===f.dataset.id);if(!t)return;const n=structuredClone(t);n.badges=n.badges||{};n.badges[f.dataset.name]=f.elements.badge.value;if(f.dataset.name==='Reduced Process')n.reducedProcess=/^(yes|true|active)$/i.test(f.elements.badge.value);try{await put('tools',{...n,updatedAt:new Date().toISOString()});await logEvent('SAVED BADGE '+n.id+' '+f.dataset.name);closeModal();await refresh();notify('Badge saved: '+n.id)}catch(e){notify('SAVE FAILED: '+e.message,true)}}
function download(name,obj){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000)}
async function exportBackup(){const data={format:'B7FI-V12-BACKUP',version:12,createdAt:new Date().toISOString(),tools:await all('tools')};download('B7-FI-Backup-'+new Date().toISOString().slice(0,10)+'.json',data);await logEvent('BACKUP EXPORTED');notify('Verified backup exported — '+data.tools.length+' tools')}
async function inspectImport(file){try{const text=await file.text();if(text.length>60_000_000)throw Error('File is too large for safe browser import');const x=JSON.parse(text);let raw=Array.isArray(x)?x:Array.isArray(x.tools)?x.tools:Array.isArray(x.state?.tools)?x.state.tools:null;if(!raw)throw Error('No tools array found in JSON');const valid=[],invalid=[],seen=new Set();for(const r of raw){if(!validTool(r)){invalid.push(clean(r?.id||'unknown'));continue}const t=normalizeTool(r);if(seen.has(t.id)){invalid.push(t.id+' (duplicate)');continue}seen.add(t.id);valid.push(t)}pendingImport=valid;modal('IMPORT PREVIEW — NO CHANGES MADE',`<p><strong>${valid.length} verified tool records</strong> · ${invalid.length} excluded invalid/duplicate records</p><p class="hint">Excluded examples: ${esc(invalid.slice(0,12).join(', ')||'None')}</p><p class="hint">Import merges by UTID. Existing matching records will be overwritten. Export a backup before importing. Microsoft List will not be changed.</p><div class="editor-actions"><button class="good" data-action="confirmimport">CONFIRM IMPORT ${valid.length} TOOLS</button><button data-action="close">CANCEL</button></div>`)}catch(e){pendingImport=null;notify('IMPORT FAILED: '+e.message,true)}}
async function commitImport(){if(!pendingImport)return;const batch=pendingImport;pendingImport=null;try{await putMany('tools',batch);await logEvent('IMPORTED '+batch.length+' TOOLS');closeModal();await refresh();notify('Imported '+batch.length+' tools; local records committed')}catch(e){notify('IMPORT FAILED: '+e.message,true)}}
async function diagnostics(){const ev=await all('events');modal('V12 DIAGNOSTICS',`<p>Local IndexedDB records: <strong>${tools.length}</strong>. No Microsoft List access is configured.</p><p class="hint">Most recent operations:</p><div class="panel">${ev.slice(-30).reverse().map(x=>`<p>${esc(x.at)} — ${esc(x.message)}</p>`).join('')||'No events yet'}</div><div class="editor-actions"><button data-action="export">EXPORT BACKUP</button><button data-action="close">CLOSE</button></div>`)}
function showPresentation(){const a=current().filter(t=>t.toolStatus!=='Archived');if(!a.length){notify('No tools to present',true);return}presentation=true;slideIndex=Math.min(slideIndex,a.length-1);$('#main').classList.add('presentation');$('#main').innerHTML=head('PRESENTATION · '+filterQuarter,`<button data-action="prev">◀ PREVIOUS</button><button data-action="next">NEXT ▶</button><button data-action="exitpresent">EXIT PRESENTATION</button>`)+card(a[slideIndex])+`<p class="muted" style="text-align:center">Tool ${slideIndex+1} of ${a.length}</p>`}
async function action(a){if(a==='add')openEditor();else if(a==='export')await exportBackup();else if(a==='import')$('#importFile').click();else if(a==='diagnostics')await diagnostics();else if(a==='close'||a==='cancel')closeModal();else if(a==='confirmimport')await commitImport();else if(a==='present')showPresentation();else if(a==='exitpresent')render();else if(a==='next'||a==='prev'){slideIndex+=a==='next'?1:-1;const n=current().filter(t=>t.toolStatus!=='Archived').length;slideIndex=(slideIndex+n)%n;showPresentation()}else if(a==='runsearch'){query=$('#searchInput')?.value||'';render()}else if(a==='editchecklist'){captureEditor();notify('Save the tool first, then open checklists from its card.');}}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-page],[data-section],[data-action],[data-edit],[data-checklist],[data-badge],[data-tab]');if(!el)return;if(el.dataset.page){page=el.dataset.page;section='live';render()}else if(el.dataset.section){section=el.dataset.section;page='operations';render()}else if(el.dataset.edit!==undefined)openEditor(el.dataset.edit);else if(el.dataset.checklist)openChecklist(el.dataset.checklist);else if(el.dataset.badge)openBadge(el.dataset.badge,el.dataset.name);else if(el.dataset.tab){captureEditor();editorTab=el.dataset.tab;editorForm()}else if(el.dataset.action)await action(el.dataset.action)});
document.addEventListener('submit',async e=>{if(['toolForm','badgeForm','checkForm'].includes(e.target.id)){e.preventDefault();if(e.target.id==='toolForm')await saveTool();else if(e.target.id==='badgeForm')await saveBadge(e.target);else await saveChecklist(e.target)}});
document.addEventListener('change',e=>{if(e.target.id==='quarterSelect'){filterQuarter=e.target.value;render()}if(e.target.id==='importFile'){const file=e.target.files[0];e.target.value='';if(file)inspectImport(file)}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(presentation)render();else closeModal()}if(e.key==='Enter'&&e.target.id==='searchInput'){e.preventDefault();query=e.target.value;render()}});
$('#modalClose').onclick=closeModal;
function sendError(message){fetch('/__client_error',{method:'POST',headers:{'Content-Type':'text/plain'},body:String(message).slice(0,4000),keepalive:true}).catch(()=>{})}
window.addEventListener('error',e=>{console.error('B7 V12',e.error||e.message);sendError(e.message);notify('APPLICATION ERROR: '+e.message,true)});
window.addEventListener('unhandledrejection',e=>{console.error('B7 V12 rejection',e.reason);sendError(e.reason?.message||e.reason);notify('UNHANDLED ERROR: '+(e.reason?.message||e.reason),true)});
try{await refresh();await logEvent('V12 FOUNDATION STARTED');notify('V12 foundation loaded · '+tools.length+' local verified tools')}catch(e){$('#main').innerHTML=`<div class="panel error-text"><h2>Database startup failed</h2><p>${esc(e.message)}</p><p>Open the Command Center using START-COMMAND-CENTER.bat on localhost, not file://.</p></div>`;console.error(e)}
