(()=>{'use strict';
const CFG={
  tenantId:'cf75356e-fe8e-498d-be4b-37ec8fbf04cf',
  clientId:'af82f005-0e21-4926-8d5d-8b6f872ab8f4',
  redirectUri:'http://localhost:5500/redirect.html',
  graph:'https://graph.microsoft.com/v1.0',
  siteHost:'kla-my.sharepoint.com',
  sitePath:'/personal/neptune_garcia_kla_com',
  listName:'B7 FI Command Center',
  scopes:['User.Read','Sites.ReadWrite.All']
};
let msalApp=null,account=null,site=null,list=null,columns=[],items=[],createdTestId=null;
const checks={signin:false,connect:false,read:false,write:false,readback:false,create:false,delete:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=(msg,kind='info')=>{let e=document.querySelector('#mu-status');if(e){e.className='mu-status '+kind;e.textContent=msg}};
function inject(){
 const style=document.createElement('style');style.textContent=`
 #mu-launch{position:static;z-index:auto;border:1px solid #54d8ff;background:#0b3150;color:#fff;font-weight:900;padding:6px 10px;border-radius:4px;cursor:pointer;box-shadow:none;white-space:nowrap;margin-right:12px}
 #mu-panel{position:fixed;inset:4vh 4vw;z-index:2147483641;background:#08131f;color:#fff;border:2px solid #176fa8;border-radius:10px;box-shadow:0 20px 80px #000b;display:none;overflow:auto;padding:22px;font-family:Arial,sans-serif}
 body.presentation-mode #mu-launch,body.presentation-mode #mu-panel,body.presentation-mode #mu-panel *{pointer-events:auto!important}\n#mu-panel.open{display:block}.mu-head{display:flex;align-items:center;justify-content:space-between;gap:15px;border-bottom:2px solid #176fa8;padding-bottom:12px}.mu-head h2{margin:0}.mu-close{font-size:28px;background:none;border:0;color:#fff;cursor:pointer}.mu-status{margin:14px 0;padding:12px;border-radius:6px;background:#16283a}.mu-status.ok{background:#123d2b}.mu-status.err{background:#511c25}.mu-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.mu-btn{background:#176fa8;color:#fff;border:1px solid #54d8ff;padding:9px 12px;border-radius:5px;font-weight:800;cursor:pointer}.mu-btn:disabled{opacity:.4;cursor:not-allowed}.mu-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px;margin:12px 0}.mu-meta div{background:#101f2e;padding:9px;border-radius:5px}.mu-table{width:100%;border-collapse:collapse;margin-top:12px;font-size:13px}.mu-table th,.mu-table td{border:1px solid #2d4961;padding:7px;vertical-align:top}.mu-table th{background:#12314b;position:sticky;top:0}.mu-table input{width:100%;box-sizing:border-box;background:#0d1c29;color:#fff;border:1px solid #45647c;padding:6px}.mu-pass{color:#29e58c}.mu-warn{color:#ffd84a}.mu-note{font-size:12px;color:#b9ccda;line-height:1.4}.mu-user{font-weight:800;color:#54d8ff}.mu-checks{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:7px;margin:12px 0}.mu-check{background:#101f2e;border:1px solid #2d4961;border-radius:5px;padding:8px;font-weight:800}.mu-check.pass{border-color:#29e58c;color:#29e58c}`;document.head.appendChild(style);
 const b=document.createElement('button');b.id='mu-launch';b.textContent='MULTI-USER TEST';const footerRight=document.querySelector('.footer-right');if(footerRight)footerRight.insertBefore(b,footerRight.firstChild);else document.body.appendChild(b);
 const p=document.createElement('section');p.id='mu-panel';p.innerHTML=`<div class="mu-head"><div><h2>B7 FI COMMAND CENTER — MULTI-USER CONNECTION TEST</h2><div class="mu-note">V6.6.22 · FULL LIST CLEAR + SHARED TOOL EDIT TEST · Microsoft Entra delegated authentication · Microsoft Graph · Microsoft List</div></div><button class="mu-close" id="mu-close">×</button></div><div id="mu-status" class="mu-status">Ready. Start the Command Center at http://localhost:5500, then sign in.</div><div class="mu-meta"><div><b>USER</b><br><span id="mu-user">Not signed in</span></div><div><b>SITE</b><br>${esc(CFG.siteHost+CFG.sitePath)}</div><div><b>LIST</b><br>${esc(CFG.listName)}</div><div><b>MODE</b><br>Shared List Test</div></div><div class="mu-checks" id="mu-checks"></div><div class="mu-actions"><button class="mu-btn" id="mu-signin">1 · SIGN IN WITH KLA</button><button class="mu-btn" id="mu-connect" disabled>2 · CONNECT + READ</button><button class="mu-btn" id="mu-refresh" disabled>3 · REFRESH / FIND EXTERNAL ROW</button><button class="mu-btn" id="mu-create" disabled>4 · CREATE TEMP TEST ROW</button><button class="mu-btn" id="mu-delete" disabled>5 · DELETE TEMP TEST ROW</button><button class="mu-btn" id="mu-signout" disabled>SIGN OUT</button></div><p class="mu-note"><b>Purpose:</b> This build preserves the current Command Center production data model while the shared-list connection is being validated. The panel below tests real multi-user read/write against the shared Microsoft List. Edit a test-row value and save it, then refresh from a second computer/user to verify shared updates. Saves use a change check to avoid silently overwriting a row changed by another user.</p><div id="mu-grid"></div>`;document.body.appendChild(p);
 b.onclick=()=>p.classList.add('open');p.querySelector('#mu-close').onclick=()=>p.classList.remove('open');
 p.querySelector('#mu-signin').onclick=signIn;p.querySelector('#mu-connect').onclick=connect;p.querySelector('#mu-refresh').onclick=loadItems;p.querySelector('#mu-create').onclick=createTempRow;p.querySelector('#mu-delete').onclick=deleteTempRow;p.querySelector('#mu-signout').onclick=signOut;renderChecks();
}
async function initMsal(){if(msalApp)return msalApp;if(!window.msal)throw new Error('Microsoft authentication library did not load. Check network access to cdn.jsdelivr.net.');msalApp=new msal.PublicClientApplication({auth:{clientId:CFG.clientId,authority:`https://login.microsoftonline.com/${CFG.tenantId}`,redirectUri:CFG.redirectUri},cache:{cacheLocation:'localStorage',storeAuthStateInCookie:false}});await msalApp.initialize();account=msalApp.getActiveAccount?.()||msalApp.getAllAccounts()[0]||null;if(account){msalApp.setActiveAccount?.(account);setSignedIn();}return msalApp}
function setSignedIn(){document.querySelector('#mu-user').textContent=account?`${account.name||account.username} (${account.username})`:'Not signed in';document.querySelector('#mu-connect').disabled=!account;document.querySelector('#mu-refresh').disabled=!list;document.querySelector('#mu-create').disabled=!list;document.querySelector('#mu-delete').disabled=!createdTestId;document.querySelector('#mu-signout').disabled=!account}
function renderChecks(){let e=document.querySelector('#mu-checks');if(!e)return;let names={signin:'SIGN IN',connect:'LIST FOUND',read:'READ',write:'UPDATE',readback:'READ-BACK',create:'CREATE',delete:'CLEANUP'};e.innerHTML=Object.entries(names).map(([k,n])=>`<div class="mu-check ${checks[k]?'pass':''}">${checks[k]?'PASS':'WAIT'} · ${n}</div>`).join('')}
function pass(k){checks[k]=true;renderChecks()}
async function signIn(){try{await initMsal();let r=await msalApp.loginPopup({scopes:CFG.scopes,redirectUri:CFG.redirectUri});account=r.account;msalApp.setActiveAccount?.(account);setSignedIn();pass('signin');status('PASS — KLA Microsoft sign-in succeeded.','ok')}catch(e){status('SIGN-IN FAILED — '+friendly(e),'err')}}
async function signOut(){try{if(msalApp&&account)await msalApp.logoutPopup({account,postLogoutRedirectUri:'http://localhost:5500/'});account=null;site=list=null;items=[];setSignedIn();document.querySelector('#mu-grid').innerHTML='';status('Signed out.')}catch(e){status('SIGN-OUT FAILED — '+friendly(e),'err')}}
async function token(){await initMsal();if(!account)throw new Error('Sign in first.');try{return (await msalApp.acquireTokenSilent({account,scopes:CFG.scopes})).accessToken}catch(e){return (await msalApp.acquireTokenPopup({account,scopes:CFG.scopes})).accessToken}}
async function graph(path,opt={}){let t=await token();let r=await fetch(CFG.graph+path,{...opt,headers:{Authorization:'Bearer '+t,'Content-Type':'application/json',...(opt.headers||{})}});let txt=await r.text(),data=null;try{data=txt?JSON.parse(txt):null}catch{}if(!r.ok){let msg=data?.error?.message||txt||`${r.status} ${r.statusText}`;throw new Error(`${r.status} — ${msg}`)}return data}
async function connect(){try{status('Connecting to Microsoft Graph…');site=await graph(`/sites/${CFG.siteHost}:${CFG.sitePath}`);let ls=await graph(`/sites/${encodeURIComponent(site.id)}/lists?$select=id,name,displayName`);list=ls.value.find(x=>(x.displayName||x.name||'').toLowerCase()===CFG.listName.toLowerCase());if(!list)throw new Error(`List “${CFG.listName}” was not found on the configured site.`);let cs=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/columns?$select=id,name,displayName,readOnly,hidden`);columns=(cs.value||[]).filter(c=>!c.hidden);pass('connect');setSignedIn();status(`PASS — Connected to “${list.displayName||list.name}”. Reading shared test tools…`,'ok');document.querySelector('#mu-refresh').disabled=false;await loadItems()}catch(e){status('CONNECTION FAILED — '+friendly(e),'err')}}
async function loadItems(){try{if(!list)return connect();status('Refreshing shared Microsoft List data…');let d=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items?$expand=fields&$top=200`);items=d.value||[];renderGrid();pass('read');status(`PASS — Read ${items.length} shared list item${items.length===1?'':'s'}. If you add a third row directly in Microsoft Lists, press 3 · REFRESH and confirm it appears here.`, 'ok')}catch(e){status('READ FAILED — '+friendly(e),'err')}}
function fieldMap(){let m={};columns.forEach(c=>m[(c.displayName||c.name).trim().toLowerCase()]=c);return m}
function val(it,label){let c=fieldMap()[label.toLowerCase()];return c?it.fields?.[c.name]??'':''}
function editableColumns(){let wanted=['Title','UTID','Code Name','FI Status','Model','Customer','Sales Order','MFG Ship Date','Quarter','Family'],m=fieldMap();return wanted.map(x=>m[x.toLowerCase()]).filter(c=>c&&!c.readOnly)}
function isShipDateCol(c){return String(c?.displayName||c?.name||'').trim().toLowerCase()==='mfg ship date'}
function cleanDate(v){let s=String(v??'').trim();if(!s)return '';let m=s.match(/^(\d{4}-\d{2}-\d{2})/);return m?m[1]:s}
function renderGrid(){let g=document.querySelector('#mu-grid'),cols=editableColumns();if(!items.length){g.innerHTML='<p class="mu-warn">The list connected successfully but contains no items.</p>';return}g.innerHTML=`<table class="mu-table"><thead><tr>${cols.map(c=>`<th>${esc(c.displayName)}</th>`).join('')}<th>LAST MODIFIED</th><th>ACTION</th></tr></thead><tbody>${items.map(it=>`<tr data-mu-row="${esc(it.id)}">${cols.map(c=>`<td><input data-field="${esc(c.name)}" value="${esc(isShipDateCol(c)?cleanDate(it.fields?.[c.name]):(it.fields?.[c.name]??''))}"></td>`).join('')}<td>${esc(it.lastModifiedDateTime||'')}</td><td><button class="mu-btn" data-mu-save="${esc(it.id)}">SAVE SHARED ROW</button></td></tr>`).join('')}</tbody></table><p class="mu-note">Tip: for the first multi-user test, change only a harmless test value such as Customer on one of the two test tools. Save, then refresh on the second user's computer.</p>`;g.querySelectorAll('[data-mu-save]').forEach(b=>b.onclick=()=>saveRow(b.dataset.muSave))}
async function saveRow(id){try{let original=items.find(x=>x.id===id),row=document.querySelector(`[data-mu-row="${CSS.escape(id)}"]`);if(!original||!row)return;status(`Checking item ${id} for another user's changes…`);let current=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}?$expand=fields`);if(original.lastModifiedDateTime&&current.lastModifiedDateTime&&original.lastModifiedDateTime!==current.lastModifiedDateTime){status(`CONFLICT — Item ${id} changed after you loaded it. Your edit was NOT saved. Refresh shared data and review the other user's changes first.`,'err');return}let body={},byName=new Map(editableColumns().map(c=>[c.name,c]));row.querySelectorAll('[data-field]').forEach(i=>{let c=byName.get(i.dataset.field),v=i.value;if(isShipDateCol(c)){v=cleanDate(v);if(!v)return}body[i.dataset.field]=v});await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}/fields`,{method:'PATCH',body:JSON.stringify(body)});pass('write');status(`PASS — Shared item ${id} saved. Reading it back now…`,`ok`);await loadItems();let verify=items.find(x=>x.id===id);if(verify){pass('readback');status(`PASS — UPDATE + READ-BACK verified for shared item ${id}.`,`ok`)}}catch(e){status('WRITE FAILED — '+friendly(e),'err')}}

async function createTempRow(){try{if(!list)return;status('Creating a temporary Microsoft List test row…');let cols=editableColumns(),body={};let title=cols.find(c=>(c.displayName||'').toLowerCase()==='title');if(title)body[title.name]='MULTI-USER TEST '+new Date().toISOString();let utid=cols.find(c=>(c.displayName||'').toLowerCase()==='utid');if(utid)body[utid.name]='MU-'+Date.now().toString().slice(-6);let r=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items`,{method:'POST',body:JSON.stringify({fields:body})});createdTestId=String(r.id);pass('create');setSignedIn();status(`PASS — Created temporary shared row ${createdTestId}. It should now be visible directly in Microsoft Lists. Refreshing…`,'ok');await loadItems()}catch(e){status('CREATE FAILED — '+friendly(e),'err')}}
async function deleteTempRow(){try{if(!createdTestId)return;let id=createdTestId;status(`Deleting temporary test row ${id}…`);await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}`,{method:'DELETE'});createdTestId=null;pass('delete');setSignedIn();await loadItems();status(`PASS — Temporary row ${id} deleted. End-to-end CREATE/READ/UPDATE/DELETE test is complete.`,'ok')}catch(e){status('DELETE FAILED — '+friendly(e),'err')}}

function friendly(e){let s=e?.message||String(e);if(/AADSTS50011/i.test(s))return s+' Redirect URI mismatch: confirm http://localhost:5500/redirect.html is registered as SPA.';if(/403|accessDenied|insufficient/i.test(s))return s+' The signed-in user or Entra app may not have the required Microsoft Graph/List permission.';return s}

// V6.6.17 — Full Scenario multi-user bridge. Scenario rows are isolated from Production.
let sharedActive=false,presenceTimer=null,lastSharedState=null,sessionId=(crypto.randomUUID?crypto.randomUUID():('S-'+Date.now()+'-'+Math.random().toString(16).slice(2)));
// V6.6.22: stable shared editing test + explicit full-list row clear; no automatic background tool refresh.
// No Graph column/schema creation is attempted. Scenario ownership is encoded in Title.
const SCN_PREFIX='B7SCN:', CHUNK_SIZE=180;
function col(label){return fieldMap()[label.toLowerCase()]}
function setField(body,label,value){let c=col(label);if(c&&!c.readOnly)body[c.name]=value}
function itemVal(it,label){let c=col(label);return c?it.fields?.[c.name]:undefined}
function titleOf(it){return String(itemVal(it,'Title')||'')}
function isScenarioRow(it){let title=titleOf(it),utid=String(itemVal(it,'UTID')||'');return title.startsWith(SCN_PREFIX)||/^SCN-.+-\d{4}$/.test(utid)||/^PRESENCE-/.test(utid)}
function isToolMeta(it){return /^B7SCN:TOOL:[^:]+:META$/.test(titleOf(it))}
function isToolChunk(it){return /^B7SCN:TOOL:[^:]+:\d{4}$/.test(titleOf(it))}
function isPresence(it){return titleOf(it).startsWith(SCN_PREFIX+'PRESENCE:')}
function toolIdFromTitle(it){let m=titleOf(it).match(/^B7SCN:TOOL:([^:]+):/);return m?m[1]:''}
async function refreshAllItems(){let d=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items?$expand=fields&$top=500`);items=d.value||[];return items}
function toolMetaFields(tool){let b={};setField(b,'Title',`${SCN_PREFIX}TOOL:${tool.id}:META`);setField(b,'UTID',tool.id);setField(b,'Code Name',tool.codename||'');setField(b,'FI Status',tool.toolStatus||'');setField(b,'Model',tool.model||'');setField(b,'Customer',tool.customer||'');setField(b,'Sales Order',tool.salesOrder||'');if(tool.shipDate)setField(b,'MFG Ship Date',cleanDate(tool.shipDate));setField(b,'Quarter',tool.quarter||'');setField(b,'Family',tool.family||'');return b}
function chunkFields(toolId,idx,chunk){let b={};setField(b,'Title',`${SCN_PREFIX}TOOL:${toolId}:${String(idx).padStart(4,'0')}`);setField(b,'UTID',`SCN-${toolId}-${String(idx).padStart(4,'0')}`);setField(b,'Code Name',chunk);return b}
async function createRow(fields){return graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items`,{method:'POST',body:JSON.stringify({fields})})}
async function patchRow(id,fields){return graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}/fields`,{method:'PATCH',body:JSON.stringify(fields)})}
async function deleteRow(id){return graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}`,{method:'DELETE'})}
async function upsertTool(tool){await refreshAllItems();let id=String(tool.id),mine=items.filter(it=>toolIdFromTitle(it)===id),meta=mine.find(isToolMeta),oldChunks=mine.filter(isToolChunk);let mf=toolMetaFields(tool);if(meta)await patchRow(meta.id,mf);else await createRow(mf);let json=JSON.stringify(tool),chunks=[];for(let i=0;i<json.length;i+=CHUNK_SIZE)chunks.push(json.slice(i,i+CHUNK_SIZE));oldChunks.sort((a,b)=>titleOf(a).localeCompare(titleOf(b)));for(let i=0;i<chunks.length;i++){let f=chunkFields(id,i,chunks[i]);if(oldChunks[i])await patchRow(oldChunks[i].id,f);else await createRow(f)}for(let i=chunks.length;i<oldChunks.length;i++)await deleteRow(oldChunks[i].id)}
function decodeSharedTools(){let groups=new Map();for(const it of items){if(!isToolMeta(it)&&!isToolChunk(it))continue;let id=toolIdFromTitle(it);if(!groups.has(id))groups.set(id,{meta:null,chunks:[]});if(isToolMeta(it))groups.get(id).meta=it;else groups.get(id).chunks.push(it)}let out=[];for(const [id,g] of groups){g.chunks.sort((a,b)=>titleOf(a).localeCompare(titleOf(b)));let raw=g.chunks.map(x=>String(itemVal(x,'Code Name')||'')).join('');try{let t=JSON.parse(raw);if(t&&t.id)out.push(t)}catch(e){console.warn('Shared Scenario tool decode failed',id,e)}}return out}
async function loadSharedScenario(localState){await refreshAllItems();let sharedTools=decodeSharedTools(),have=new Set(sharedTools.map(t=>String(t.id)));for(const t of localState.tools||[])if(!have.has(String(t.id)))await upsertTool(t);await refreshAllItems();sharedTools=decodeSharedTools();let out=JSON.parse(JSON.stringify(localState));out.environment='SCENARIO TEST';out.tools=sharedTools.length?sharedTools:localState.tools;lastSharedState=JSON.parse(JSON.stringify(out));return out}
async function syncChangedTools(nextState){if(!sharedActive||!list)return;let prev=new Map((lastSharedState?.tools||[]).map(t=>[String(t.id),JSON.stringify(t)]));let changed=(nextState.tools||[]).filter(t=>prev.get(String(t.id))!==JSON.stringify(t));for(const t of changed)await upsertTool(t);lastSharedState=JSON.parse(JSON.stringify(nextState));await heartbeat();updateFooter('SCENARIO TEST')}
let syncChain=Promise.resolve();
function queueStateSync(st,msg){let snap=JSON.parse(JSON.stringify(st));syncChain=syncChain.then(()=>syncChangedTools(snap)).catch(e=>{console.error(e);setFooterStatus('SCENARIO TEST · SYNC ERROR')})}
async function heartbeat(){if(!sharedActive||!list||!account)return;await refreshAllItems();let key=SCN_PREFIX+'PRESENCE:'+sessionId,mine=items.find(it=>titleOf(it)===key),b={};setField(b,'Title',key);setField(b,'UTID','PRESENCE-'+sessionId.slice(0,20));setField(b,'Code Name',account.name||account.username||'Unknown');setField(b,'Customer',account.username||'');setField(b,'Quarter',new Date().toISOString());if(mine)await patchRow(mine.id,b);else await createRow(b);await refreshAllItems()}
function activeUserDetails(){let cutoff=Date.now()-120000,seen=new Map();for(const it of items.filter(isPresence)){let name=String(itemVal(it,'Code Name')||'Unknown'),email=String(itemVal(it,'Customer')||''),lastSeen=String(itemVal(it,'Quarter')||'');let ts=Date.parse(lastSeen);if(ts>=cutoff)seen.set(email||name,{name,email,lastSeen,sessionId:titleOf(it).slice((SCN_PREFIX+'PRESENCE:').length)})}return [...seen.values()]}
function activeUsers(){return activeUserDetails().map(x=>x.name)}
function setFooterStatus(txt){let e=document.querySelector('#sharedStatus');if(e)e.textContent=txt}
function updateFooter(env){let ident=document.querySelector('#sharedIdentity'),au=document.querySelector('#activeUsers');if(env==='PRODUCTION'){if(ident)ident.textContent='LOCAL';setFooterStatus('PRODUCTION · LIST OFFLINE');if(au)au.textContent='USERS: —';return}if(ident)ident.textContent=account?'SIGNED IN: '+String(account.name||account.username).split(' ')[0].toUpperCase():'NOT SIGNED IN';setFooterStatus(sharedActive?'SCENARIO TEST · LIST CONNECTED':'SCENARIO TEST · LIST OFFLINE');if(au)au.textContent='USERS: '+activeUsers().length}
function showActiveUsers(){let old=document.querySelector('#mu-users-panel');if(old)old.remove();let u=activeUserDetails(),p=document.createElement('div');p.id='mu-users-panel';p.className='mu-users-panel';p.innerHTML=`<div class="mu-users-card"><button class="mu-users-x">×</button><h2>ACTIVE COMMAND CENTER USERS</h2><p class="mu-note">Users are active when their shared Scenario session checked in during the last 2 minutes.</p>${u.length?u.map(x=>`<div class="mu-user-row"><b>● ${esc(x.name)}</b><span>${esc(x.email)}</span><small>Last activity: ${esc(x.lastSeen?new Date(x.lastSeen).toLocaleString():'Unknown')}</small></div>`).join(''):'<div class="mu-user-row"><b>NO ACTIVE SHARED USERS</b></div>'}</div>`;document.body.appendChild(p);p.querySelector('.mu-users-x').onclick=()=>p.remove();p.onclick=e=>{if(e.target===p)p.remove()}}
async function clearEntireList(){await initMsal();if(!account){let r=await msalApp.loginPopup({scopes:CFG.scopes,redirectUri:CFG.redirectUri});account=r.account;msalApp.setActiveAccount?.(account);setSignedIn();pass('signin')}if(!list)await connect();await refreshAllItems();let doomed=[...items],deleted=0,failed=[];status(`CLEAR LIST — deleting ${doomed.length} Microsoft List row(s)…`);for(const it of doomed){try{await deleteRow(it.id);deleted++}catch(e){failed.push({id:it.id,error:friendly(e)})}}await refreshAllItems();let remaining=items.length;if(remaining||failed.length){setFooterStatus(`LIST CLEAR INCOMPLETE · ${remaining} ROWS REMAIN`);status(`CLEAR LIST INCOMPLETE — deleted ${deleted} row(s); ${remaining} row(s) remain.`, 'err');throw new Error(`${remaining} row(s) remain after full-list clear verification.`)}lastSharedState=null;sharedActive=false;clearInterval(presenceTimer);presenceTimer=null;let empty={environment:'SCENARIO TEST',tools:[]};if(window.B7ApplySharedScenario)window.B7ApplySharedScenario(empty);updateFooter('SCENARIO TEST');setFooterStatus('SHARED SCENARIO TEST · LIST EMPTY');status(`PASS — MICROSOFT LIST CLEAR VERIFIED. Deleted ${deleted} row(s). List schema/columns were not changed. Click START SHARED SCENARIO to repopulate the List from the standard six-tool Scenario dataset.`, 'ok');return deleted}
async function resetSharedScenario(){await initMsal();if(!account){let r=await msalApp.loginPopup({scopes:CFG.scopes,redirectUri:CFG.redirectUri});account=r.account;msalApp.setActiveAccount?.(account);setSignedIn()}if(!list)await connect();await refreshAllItems();let doomed=items.filter(isScenarioRow),deleted=0,failed=[];for(const it of doomed){try{await deleteRow(it.id);deleted++}catch(e){failed.push({id:it.id,error:friendly(e)})}}await refreshAllItems();let remaining=items.filter(isScenarioRow);sharedActive=false;clearInterval(presenceTimer);presenceTimer=null;lastSharedState=null;if(remaining.length||failed.length){setFooterStatus('SCENARIO TEST · RESET INCOMPLETE');status(`RESET INCOMPLETE — deleted ${deleted} Scenario row(s); ${remaining.length} Scenario row(s) remain. Command Center data was retained.`,'err');throw new Error(`${remaining.length} Scenario row(s) remain after reset verification.`)}let empty={environment:'SCENARIO TEST',tools:[]};if(window.B7ApplySharedScenario)window.B7ApplySharedScenario(empty);updateFooter('SCENARIO TEST');setFooterStatus('SHARED SCENARIO TEST · EMPTY');status(`PASS — Shared Scenario reset verified. Deleted ${deleted} Scenario/Presence row(s). Production/local data was not changed.`,'ok');return deleted}
async function refreshScenario(){if(!sharedActive)throw new Error('Start Shared Scenario first.');let seed=lastSharedState||{environment:'SCENARIO TEST',tools:[]};await refreshAllItems();let tools=decodeSharedTools();if(!tools.length&&(seed.tools||[]).length){setFooterStatus(`SCENARIO TEST · SYNC WARNING · ${(seed.tools||[]).length} TOOLS RETAINED`);status('SYNC WARNING — Shared read returned no valid reconstructed tools. Last known-good Command Center data was retained.','err');return JSON.parse(JSON.stringify(seed))}let out=JSON.parse(JSON.stringify(seed));out.environment='SCENARIO TEST';out.tools=tools;lastSharedState=JSON.parse(JSON.stringify(out));updateFooter('SCENARIO TEST');return out}
async function enterScenario(localState){await initMsal();if(!account){let r=await msalApp.loginPopup({scopes:CFG.scopes,redirectUri:CFG.redirectUri});account=r.account;msalApp.setActiveAccount?.(account);setSignedIn();pass('signin')}if(!list)await connect();sharedActive=true;let out=await loadSharedScenario(localState);clearInterval(presenceTimer);presenceTimer=null;updateFooter('SCENARIO TEST');status('PASS — SHARED SCENARIO ACTIVE. Automatic background tool refresh is disabled in V6.6.22. Use normal Command Center edits + SAVE, then REFRESH SHARED DATA to verify List persistence.','ok');return out}
function leaveScenario(){sharedActive=false;clearInterval(presenceTimer);presenceTimer=null;updateFooter('PRODUCTION')}
window.B7Shared={enterScenario,leaveScenario,queueStateSync,isActive:()=>sharedActive,updateFooter,resetSharedScenario,clearEntireList,refreshScenario,showActiveUsers,activeUsers};

document.addEventListener('DOMContentLoaded',async()=>{inject();document.querySelector('#activeUsers')?.addEventListener('click',showActiveUsers);try{await initMsal();if(account)status('Existing Microsoft sign-in detected. You can connect to the shared List.','ok')}catch(e){status('Authentication setup warning — '+friendly(e),'err')}});
})();
