(()=>{'use strict';
const CFG={
  tenantId:'cf75356e-fe8e-498d-be4b-37ec8fbf04cf',
  clientId:'af82f005-0e21-4926-8d5d-8b6f872ab8f4',
  redirectUri:'http://localhost:5500/redirect.html',
  graph:'https://graph.microsoft.com/v1.0',
  siteHost:'kla-my.sharepoint.com',
  sitePath:'/personal/neptune_garcia_kla_com',
  listName:'B7 FI Command Center',
  scopes:['User.Read','Sites.ReadWrite.All']
};
let msalApp=null,account=null,site=null,list=null,columns=[],items=[],createdTestId=null;
const checks={signin:false,connect:false,read:false,write:false,readback:false,create:false,delete:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=(msg,kind='info')=>{let e=document.querySelector('#mu-status');if(e){e.className='mu-status '+kind;e.textContent=msg}};
function inject(){
 const style=document.createElement('style');style.textContent=`
 #mu-launch{position:static;z-index:auto;border:1px solid #54d8ff;background:#0b3150;color:#fff;font-weight:900;padding:6px 10px;border-radius:4px;cursor:pointer;box-shadow:none;white-space:nowrap;margin-right:12px}
 #mu-panel{position:fixed;inset:4vh 4vw;z-index:2147483641;background:#08131f;color:#fff;border:2px solid #176fa8;border-radius:10px;box-shadow:0 20px 80px #000b;display:none;overflow:auto;padding:22px;font-family:Arial,sans-serif}
 body.presentation-mode #mu-launch,body.presentation-mode #mu-panel,body.presentation-mode #mu-panel *{pointer-events:auto!important}\n#mu-panel.open{display:block}.mu-head{display:flex;align-items:center;justify-content:space-between;gap:15px;border-bottom:2px solid #176fa8;padding-bottom:12px}.mu-head h2{margin:0}.mu-close{font-size:28px;background:none;border:0;color:#fff;cursor:pointer}.mu-status{margin:14px 0;padding:12px;border-radius:6px;background:#16283a}.mu-status.ok{background:#123d2b}.mu-status.err{background:#511c25}.mu-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.mu-btn{background:#176fa8;color:#fff;border:1px solid #54d8ff;padding:9px 12px;border-radius:5px;font-weight:800;cursor:pointer}.mu-btn:disabled{opacity:.4;cursor:not-allowed}.mu-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px;margin:12px 0}.mu-meta div{background:#101f2e;padding:9px;border-radius:5px}.mu-table{width:100%;border-collapse:collapse;margin-top:12px;font-size:13px}.mu-table th,.mu-table td{border:1px solid #2d4961;padding:7px;vertical-align:top}.mu-table th{background:#12314b;position:sticky;top:0}.mu-table input{width:100%;box-sizing:border-box;background:#0d1c29;color:#fff;border:1px solid #45647c;padding:6px}.mu-pass{color:#29e58c}.mu-warn{color:#ffd84a}.mu-note{font-size:12px;color:#b9ccda;line-height:1.4}.mu-user{font-weight:800;color:#54d8ff}.mu-checks{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:7px;margin:12px 0}.mu-check{background:#101f2e;border:1px solid #2d4961;border-radius:5px;padding:8px;font-weight:800}.mu-check.pass{border-color:#29e58c;color:#29e58c}`;document.head.appendChild(style);
 const b=document.createElement('button');b.id='mu-launch';b.textContent='MULTI-USER DIAGNOSTICS';b.className='btn';b.hidden=true;document.body.appendChild(b);
 // V6.6.46: keep the internal diagnostics launcher hidden. The single visible Administration Center button opens it through data-shared-action=diagnostics.
 b.hidden=true;
 const p=document.createElement('section');p.id='mu-panel';p.innerHTML=`<div class="mu-head"><div><h2>B7 FI COMMAND CENTER — MULTI-USER CONNECTION TEST</h2><div class="mu-note">V7.0.1 · ONE TOOL = ONE ROW MULTI-USER TEST · Microsoft Entra delegated authentication · Microsoft Graph · Microsoft List</div></div><button class="mu-close" id="mu-close">×</button></div><div id="mu-status" class="mu-status">Ready. Start the Command Center at http://localhost:5500, then sign in.</div><div class="mu-meta"><div><b>USER</b><br><span id="mu-user">Not signed in</span></div><div><b>SITE</b><br>${esc(CFG.siteHost+CFG.sitePath)}</div><div><b>LIST</b><br>${esc(CFG.listName)}</div><div><b>MODE</b><br>Shared List Test</div></div><div class="mu-checks" id="mu-checks"></div><div class="mu-actions"><button class="mu-btn" id="mu-signin">1 · SIGN IN WITH KLA</button><button class="mu-btn" id="mu-connect" disabled>2 · CONNECT + READ</button><button class="mu-btn" id="mu-refresh" disabled>3 · REFRESH / FIND EXTERNAL ROW</button><button class="mu-btn" id="mu-create" disabled>4 · CREATE TEMP TEST ROW</button><button class="mu-btn" id="mu-delete" disabled>5 · DELETE TEMP TEST ROW</button><button class="mu-btn" id="mu-signout" disabled>SIGN OUT</button></div><p class="mu-note"><b>Purpose:</b> This build preserves the current Command Center production data model while the shared-list connection is being validated. The panel below tests real multi-user read/write against the shared Microsoft List. Edit a test-row value and save it, then refresh from a second computer/user to verify shared updates. Saves use a change check to avoid silently overwriting a row changed by another user.</p><div id="mu-grid"></div>`;document.body.appendChild(p);
 b.onclick=()=>p.classList.add('open');p.querySelector('#mu-close').onclick=()=>p.classList.remove('open');
 p.querySelector('#mu-signin').onclick=signIn;p.querySelector('#mu-connect').onclick=connect;p.querySelector('#mu-refresh').onclick=loadItems;p.querySelector('#mu-create').onclick=createTempRow;p.querySelector('#mu-delete').onclick=deleteTempRow;p.querySelector('#mu-signout').onclick=signOut;renderChecks();
}
async function initMsal(){if(msalApp)return msalApp;if(!window.msal)throw new Error('Microsoft authentication library did not load. Check network access to cdn.jsdelivr.net.');msalApp=new msal.PublicClientApplication({auth:{clientId:CFG.clientId,authority:`https://login.microsoftonline.com/${CFG.tenantId}`,redirectUri:CFG.redirectUri},cache:{cacheLocation:'localStorage',storeAuthStateInCookie:false}});await msalApp.initialize();account=msalApp.getActiveAccount?.()||msalApp.getAllAccounts()[0]||null;if(account){msalApp.setActiveAccount?.(account);setSignedIn();}return msalApp}
function setSignedIn(){document.querySelector('#mu-user').textContent=account?`${account.name||account.username} (${account.username})`:'Not signed in';document.querySelector('#mu-connect').disabled=!account;document.querySelector('#mu-refresh').disabled=!list;document.querySelector('#mu-create').disabled=!list;document.querySelector('#mu-delete').disabled=!createdTestId;document.querySelector('#mu-signout').disabled=!account}
function renderChecks(){let e=document.querySelector('#mu-checks');if(!e)return;let names={signin:'SIGN IN',connect:'LIST FOUND',read:'READ',write:'UPDATE',readback:'READ-BACK',create:'CREATE',delete:'CLEANUP'};e.innerHTML=Object.entries(names).map(([k,n])=>`<div class="mu-check ${checks[k]?'pass':''}">${checks[k]?'PASS':'WAIT'} · ${n}</div>`).join('')}
function pass(k){checks[k]=true;renderChecks()}
async function signIn(){try{await initMsal();let r=await msalApp.loginPopup({scopes:CFG.scopes,redirectUri:CFG.redirectUri});account=r.account;msalApp.setActiveAccount?.(account);setSignedIn();pass('signin');status('PASS — KLA Microsoft sign-in succeeded.','ok')}catch(e){status('SIGN-IN FAILED — '+friendly(e),'err')}}
async function signOut(){try{if(msalApp&&account)await msalApp.logoutPopup({account,postLogoutRedirectUri:'http://localhost:5500/'});account=null;site=list=null;items=[];setSignedIn();document.querySelector('#mu-grid').innerHTML='';status('Signed out.')}catch(e){status('SIGN-OUT FAILED — '+friendly(e),'err')}}
async function token(){await initMsal();if(!account)throw new Error('Sign in first.');try{return (await msalApp.acquireTokenSilent({account,scopes:CFG.scopes})).accessToken}catch(e){return (await msalApp.acquireTokenPopup({account,scopes:CFG.scopes})).accessToken}}
async function graph(path,opt={}){let t=await token();let r=await fetch(CFG.graph+path,{...opt,headers:{Authorization:'Bearer '+t,'Content-Type':'application/json',...(opt.headers||{})}});let txt=await r.text(),data=null;try{data=txt?JSON.parse(txt):null}catch{}if(!r.ok){let msg=data?.error?.message||txt||`${r.status} ${r.statusText}`;throw new Error(`${r.status} — ${msg}`)}return data}
async function connect(){try{status('Connecting to Microsoft Graph…');site=await graph(`/sites/${CFG.siteHost}:${CFG.sitePath}`);let ls=await graph(`/sites/${encodeURIComponent(site.id)}/lists?$select=id,name,displayName`);list=ls.value.find(x=>(x.displayName||x.name||'').toLowerCase()===CFG.listName.toLowerCase());if(!list)throw new Error(`List “${CFG.listName}” was not found on the configured site.`);let cs=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/columns?$select=id,name,displayName,readOnly,hidden`);columns=(cs.value||[]).filter(c=>!c.hidden);pass('connect');setSignedIn();status(`PASS — Connected to “${list.displayName||list.name}”. Reading shared test tools…`,'ok');document.querySelector('#mu-refresh').disabled=false;await loadItems()}catch(e){status('CONNECTION FAILED — '+friendly(e),'err')}}
async function loadItems(){try{if(!list)return connect();status('Refreshing shared Microsoft List data…');let d=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items?$expand=fields&$top=200`);items=d.value||[];renderGrid();pass('read');status(`PASS — Read ${items.length} shared list item${items.length===1?'':'s'}. If you add a third row directly in Microsoft Lists, press 3 · REFRESH and confirm it appears here.`, 'ok')}catch(e){status('READ FAILED — '+friendly(e),'err')}}
function fieldMap(){let m={};columns.forEach(c=>m[(c.displayName||c.name).trim().toLowerCase()]=c);return m}
function val(it,label){let c=fieldMap()[label.toLowerCase()];return c?it.fields?.[c.name]??'':''}
function editableColumns(){let wanted=['Title','UTID','Code Name','FI Status','Model','Customer','Sales Order','MFG Ship Date','Quarter','Family'],m=fieldMap();return wanted.map(x=>m[x.toLowerCase()]).filter(c=>c&&!c.readOnly)}
function isShipDateCol(c){return String(c?.displayName||c?.name||'').trim().toLowerCase()==='mfg ship date'}
function cleanDate(v){let s=String(v??'').trim();if(!s)return '';let m=s.match(/^(\d{4}-\d{2}-\d{2})/);return m?m[1]:s}
function renderGrid(){let g=document.querySelector('#mu-grid'),cols=editableColumns();if(!items.length){g.innerHTML='<p class="mu-warn">The list connected successfully but contains no items.</p>';return}g.innerHTML=`<table class="mu-table"><thead><tr>${cols.map(c=>`<th>${esc(c.displayName)}</th>`).join('')}<th>LAST MODIFIED</th><th>ACTION</th></tr></thead><tbody>${items.map(it=>`<tr data-mu-row="${esc(it.id)}">${cols.map(c=>`<td><input data-field="${esc(c.name)}" value="${esc(isShipDateCol(c)?cleanDate(it.fields?.[c.name]):(it.fields?.[c.name]??''))}"></td>`).join('')}<td>${esc(it.lastModifiedDateTime||'')}</td><td><button class="mu-btn" data-mu-save="${esc(it.id)}">SAVE SHARED ROW</button></td></tr>`).join('')}</tbody></table><p class="mu-note">Tip: for the first multi-user test, change only a harmless test value such as Customer on one of the two test tools. Save, then refresh on the second user's computer.</p>`;g.querySelectorAll('[data-mu-save]').forEach(b=>b.onclick=()=>saveRow(b.dataset.muSave))}
async function saveRow(id){try{let original=items.find(x=>x.id===id),row=document.querySelector(`[data-mu-row="${CSS.escape(id)}"]`);if(!original||!row)return;status(`Checking item ${id} for another user's changes…`);let current=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}?$expand=fields`);if(original.lastModifiedDateTime&&current.lastModifiedDateTime&&original.lastModifiedDateTime!==current.lastModifiedDateTime){status(`CONFLICT — Item ${id} changed after you loaded it. Your edit was NOT saved. Refresh shared data and review the other user's changes first.`,'err');return}let body={},byName=new Map(editableColumns().map(c=>[c.name,c]));row.querySelectorAll('[data-field]').forEach(i=>{let c=byName.get(i.dataset.field),v=i.value;if(isShipDateCol(c)){v=cleanDate(v);if(!v)return}body[i.dataset.field]=v});await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}/fields`,{method:'PATCH',body:JSON.stringify(body)});pass('write');status(`PASS — Shared item ${id} saved. Reading it back now…`,`ok`);await loadItems();let verify=items.find(x=>x.id===id);if(verify){pass('readback');status(`PASS — UPDATE + READ-BACK verified for shared item ${id}.`,`ok`)}}catch(e){status('WRITE FAILED — '+friendly(e),'err')}}

async function createTempRow(){try{if(!list)return;status('Creating a temporary Microsoft List test row…');let cols=editableColumns(),body={};let title=cols.find(c=>(c.displayName||'').toLowerCase()==='title');if(title)body[title.name]='MULTI-USER TEST '+new Date().toISOString();let utid=cols.find(c=>(c.displayName||'').toLowerCase()==='utid');if(utid)body[utid.name]='MU-'+Date.now().toString().slice(-6);let r=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items`,{method:'POST',body:JSON.stringify({fields:body})});createdTestId=String(r.id);pass('create');setSignedIn();status(`PASS — Created temporary shared row ${createdTestId}. It should now be visible directly in Microsoft Lists. Refreshing…`,'ok');await loadItems()}catch(e){status('CREATE FAILED — '+friendly(e),'err')}}
async function deleteTempRow(){try{if(!createdTestId)return;let id=createdTestId;status(`Deleting temporary test row ${id}…`);await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}`,{method:'DELETE'});createdTestId=null;pass('delete');setSignedIn();await loadItems();status(`PASS — Temporary row ${id} deleted. End-to-end CREATE/READ/UPDATE/DELETE test is complete.`,'ok')}catch(e){status('DELETE FAILED — '+friendly(e),'err')}}

function friendly(e){let s=e?.message||String(e);if(/AADSTS50011/i.test(s))return s+' Redirect URI mismatch: confirm http://localhost:5500/redirect.html is registered as SPA.';if(/403|accessDenied|insufficient/i.test(s))return s+' The signed-in user or Entra app may not have the required Microsoft Graph/List permission.';return s}

// V6.6.45 — One Tool = One Microsoft List Row shared-data bridge.
// REQUIRED LIST SCHEMA: Title (default) + a Multiple lines of text column named "Tool Data".
// Optional friendly columns (UTID, Code Name, FI Status, Model, Customer, Sales Order, MFG Ship Date, Quarter, Family)
// are populated when present, but the complete UTC state lives in Tool Data so one physical tool stays one List item.
let sharedActive=false,presenceTimer=null,lastSharedState=null,sessionId=(crypto.randomUUID?crypto.randomUUID():('S-'+Date.now()+'-'+Math.random().toString(16).slice(2)));
const TOOL_PREFIX='B7TOOL:', TOOL_DATA_LABEL='Tool Data', SHARED_MODE_KEY='b7fi-shared-mode-active-v6643';
function col(label){return fieldMap()[label.toLowerCase()]}
function setField(body,label,value){let c=col(label);if(c&&!c.readOnly)body[c.name]=value}
function itemVal(it,label){let c=col(label);return c?it.fields?.[c.name]:undefined}
function titleOf(it){return String(itemVal(it,'Title')||'')}
function isToolRow(it){return titleOf(it).startsWith(TOOL_PREFIX)}
function toolIdFromRow(it){let t=titleOf(it);return t.startsWith(TOOL_PREFIX)?t.slice(TOOL_PREFIX.length):''}
function requireToolDataColumn(){let c=col(TOOL_DATA_LABEL);if(!c||c.readOnly)throw new Error('ONE-ROW SCHEMA REQUIRED — Add a Microsoft List column named “Tool Data” with type Multiple lines of text, then reconnect. V7.0.1 will not create chunk rows.');return c}
async function refreshAllItems(){let all=[],path=`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items?$expand=fields&$top=200`;while(path){let d=await graph(path.replace(CFG.graph,''));all.push(...(d.value||[]));path=d['@odata.nextLink']||''}items=all;return items}
function toolRowFields(tool){requireToolDataColumn();let b={};setField(b,'Title',TOOL_PREFIX+String(tool.id));setField(b,TOOL_DATA_LABEL,JSON.stringify(tool));setField(b,'UTID',tool.id);setField(b,'Code Name',tool.codename||'');setField(b,'FI Status',tool.toolStatus||'');setField(b,'Model',tool.model||'');setField(b,'Customer',tool.customer||'');setField(b,'Sales Order',tool.salesOrder||'');if(tool.shipDate)setField(b,'MFG Ship Date',cleanDate(tool.shipDate));setField(b,'Quarter',tool.quarter||'');setField(b,'Family',tool.family||'');setField(b,'Last Updated By',account?.username||account?.name||'');setField(b,'Revision',String((Number(tool._sharedRevision)||0)+1));return b}
async function createRow(fields){return graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items`,{method:'POST',body:JSON.stringify({fields})})}
async function patchRow(id,fields){return graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}/fields`,{method:'PATCH',body:JSON.stringify(fields)})}
async function deleteRow(id){try{return await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}`,{method:'DELETE'})}catch(e){if(String(e.message||'').startsWith('404'))return null;throw e}}
async function upsertTool(tool){requireToolDataColumn();await refreshAllItems();let id=String(tool.id),matches=items.filter(it=>isToolRow(it)&&toolIdFromRow(it)===id),row=matches[0],f=toolRowFields(tool);if(row)await patchRow(row.id,f);else await createRow(f);for(const extra of matches.slice(1))await deleteRow(extra.id)}
function decodeSharedTools(){requireToolDataColumn();let out=[];for(const it of items.filter(isToolRow)){let raw=String(itemVal(it,TOOL_DATA_LABEL)||'');if(!raw)continue;try{let t=JSON.parse(raw);if(t&&t.id)out.push(t)}catch(e){console.warn('One-row shared tool decode failed',toolIdFromRow(it),e)}}return out}
async function loadSharedScenario(localState){requireToolDataColumn();await refreshAllItems();let sharedTools=decodeSharedTools(),have=new Set(sharedTools.map(t=>String(t.id)));for(const t of localState.tools||[])if(!have.has(String(t.id)))await upsertTool(t);await refreshAllItems();sharedTools=decodeSharedTools();let out=JSON.parse(JSON.stringify(localState));out.environment='SCENARIO TEST';out.tools=sharedTools;lastSharedState=JSON.parse(JSON.stringify(out));return out}
async function syncChangedTools(nextState){if(!sharedActive||!list)return;requireToolDataColumn();let prev=new Map((lastSharedState?.tools||[]).map(t=>[String(t.id),JSON.stringify(t)]));let changed=(nextState.tools||[]).filter(t=>prev.get(String(t.id))!==JSON.stringify(t));for(const t of changed)await upsertTool(t);await refreshAllItems();lastSharedState=JSON.parse(JSON.stringify(nextState));updateFooter('SCENARIO TEST')}
let syncChain=Promise.resolve();
function queueStateSync(st,msg){let snap=JSON.parse(JSON.stringify(st));syncChain=syncChain.then(()=>syncChangedTools(snap)).catch(e=>{console.error(e);setFooterStatus('SCENARIO TEST · SYNC ERROR');status('SHARED SAVE FAILED — '+friendly(e),'err')})}
function activeUserDetails(){return []}
function activeUsers(){return account?[String(account.name||account.username||'').trim()]:[]}
function setFooterStatus(txt){let e=document.querySelector('#sharedStatus');if(e)e.textContent=txt}
function setModeIdentity(mode,connection){let shared=mode==='shared',connected=connection==='connected',connecting=connection==='connecting';for(const id of ['headerModeCenter','footerModeCenter']){let e=document.getElementById(id);if(e){e.classList.toggle('shared-connected',shared&&connected);e.classList.toggle('shared-connecting',shared&&connecting);e.classList.toggle('shared-disconnected',shared&&!connected&&!connecting)}}let h=document.getElementById('headerModeLabel'),hc=document.getElementById('headerConnectionLabel'),f=document.getElementById('footerModeLabel'),fc=document.getElementById('footerConnectionLabel');if(h)h.textContent=shared?'MULTI-USER MODE':'LOCAL PRODUCTION';if(f)f.textContent=shared?'MULTI-USER':'LOCAL';let txt=shared?(connected?'MICROSOFT LIST CONNECTED':connecting?'CONNECTING TO LIST':'LIST DISCONNECTED'):'LOCAL DATA';if(hc)hc.textContent=txt;if(fc)fc.textContent=txt}
function renderPresenceBadges(){
  const names=['Kenny','Hailey','Tony','Miguel','Saidomar','Benson','Neptune'];
  const host=document.querySelector('#presenceBadges');if(!host)return;
  const who=String(account?.name||account?.username||'').toLowerCase();
  host.innerHTML=names.map(n=>{let mine=who.includes(n.toLowerCase()),active=sharedActive&&mine;return `<button type="button" class="presence-badge ${active?'active':''} ${mine?'me':''}" data-presence-user="${n}">${n.toUpperCase()}</button>`}).join('');
}
function updateFooter(env){
  let au=document.querySelector('#activeUsers'),health=document.querySelector('#footerDataHealth'),sync=document.querySelector('#footerLastSync');
  renderPresenceBadges();
  if(env==='PRODUCTION'){
    setFooterStatus('LOCAL DATA');if(au)au.textContent='USERS: —/7';if(health)health.textContent=`DATA HEALTH: ${window.state?.tools?.length||0} LOCAL TOOLS`;if(sync)sync.textContent='LAST SYNC: LOCAL';setModeIdentity('local','offline');return;
  }
  setFooterStatus(sharedActive?'LIST CONNECTED · 1 ROW/TOOL':'LIST DISCONNECTED');
  if(au)au.textContent=sharedActive?'USERS: 1/7':'USERS: 0/7';
  if(health)health.textContent=`DATA HEALTH: ${sharedActive?'SHARED READY':'WAITING'}`;
  if(sync)sync.textContent=sharedActive?'LAST SYNC: '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):'LAST SYNC: —';
  setModeIdentity('shared',sharedActive?'connected':'offline');renderPresenceBadges();
}
function showActiveUsers(){alert('ACTIVE USERS presence rows are temporarily disabled in V6.6.45 while the one-tool/one-row storage model is validated.')}
function downloadJson(obj,name){let blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function ensureConnected(){await initMsal();if(!account){let r=await msalApp.loginPopup({scopes:CFG.scopes,redirectUri:CFG.redirectUri});account=r.account;msalApp.setActiveAccount?.(account);setSignedIn();pass('signin')}if(!list)await connect();await refreshAllItems()}
function writableFieldSet(){let set=new Set();for(const c of columns||[]){if(c&&c.name&&!c.readOnly&&!c.hidden)set.add(c.name)}return set}
function backupPayload(){return {format:'B7-FI-SHARED-LIST-BACKUP',version:'6.6.43',storageModel:'ONE-TOOL-ONE-ROW',createdAt:new Date().toISOString(),siteHost:CFG.siteHost,sitePath:CFG.sitePath,listName:CFG.listName,rowCount:items.length,rows:items.map(it=>({fields:{...(it.fields||{})}}))}}
async function exportSharedBackup(prefix='B7-FI-SHARED-LIST-BACKUP'){await ensureConnected();let data=backupPayload(),stamp=new Date().toISOString().replace(/[:.]/g,'-');downloadJson(data,`${prefix}-${stamp}.json`);status(`PASS — Shared backup exported with ${data.rowCount} List row(s).`,'ok');return {count:data.rowCount,data}}
async function restoreSharedBackup(data){if(!data||data.format!=='B7-FI-SHARED-LIST-BACKUP'||!Array.isArray(data.rows))throw new Error('Selected file is not a valid B7 FI shared List backup.');await ensureConnected();requireToolDataColumn();await exportSharedBackup('B7-FI-PRE-RESTORE-SHARED-BACKUP');for(const it of [...items])await deleteRow(it.id);await refreshAllItems();if(items.length)throw new Error(`${items.length} row(s) remain after pre-restore clear.`);let writable=writableFieldSet(),restored=0;for(const row of data.rows){let f={};for(const [k,v] of Object.entries(row.fields||{})){if(writable.has(k))f[k]=v}if(!Object.keys(f).length)continue;await createRow(f);restored++}await refreshAllItems();if(items.length!==restored)throw new Error(`Restore verification mismatch: restored ${restored}, read back ${items.length}.`);let tools=decodeSharedTools(),out={environment:'SCENARIO TEST',tools};lastSharedState=JSON.parse(JSON.stringify(out));sharedActive=true;updateFooter('SCENARIO TEST');status(`PASS — Shared backup restored and verified: ${restored} row(s), ${tools.length} tool(s).`,'ok');return {count:restored,state:out}}
async function replaceSharedScenario(localState){await ensureConnected();requireToolDataColumn();for(const it of [...items])await deleteRow(it.id);await refreshAllItems();if(items.length)throw new Error(`${items.length} row(s) remain; shared test dataset was not started.`);sharedActive=true;localStorage.setItem(SHARED_MODE_KEY,'1');lastSharedState=null;let out=JSON.parse(JSON.stringify(localState||{environment:'SCENARIO TEST',tools:[]}));out.environment='SCENARIO TEST';for(const t of out.tools||[])await upsertTool(t);await refreshAllItems();let decoded=decodeSharedTools();if(items.filter(isToolRow).length!==decoded.length)throw new Error('ONE-ROW VERIFICATION FAILED — List row/tool count mismatch.');out.tools=decoded;lastSharedState=JSON.parse(JSON.stringify(out));updateFooter('SCENARIO TEST');status(`PASS — ONE TOOL = ONE ROW verified: ${decoded.length} tool(s), ${items.filter(isToolRow).length} tool row(s).`,'ok');return out}
async function clearEntireList(){await ensureConnected();let doomed=[...items],deleted=0,failed=[];status(`SHARED MASTER RESET — deleting ${doomed.length} Microsoft List row(s)…`);for(const it of doomed){try{await deleteRow(it.id);deleted++}catch(e){failed.push({id:it.id,error:friendly(e)})}}await refreshAllItems();let remaining=items.length;if(remaining||failed.length){setFooterStatus(`LIST CLEAR INCOMPLETE · ${remaining} ROWS REMAIN`);throw new Error(`MASTER RESET INCOMPLETE — deleted ${deleted}; ${remaining} remain; ${failed.length} failed.`)}lastSharedState=null;sharedActive=false;localStorage.removeItem(SHARED_MODE_KEY);let empty={environment:'SCENARIO TEST',tools:[]};if(window.B7ApplySharedScenario)window.B7ApplySharedScenario(empty);updateFooter('SCENARIO TEST');setFooterStatus('SHARED SCENARIO TEST · LIST EMPTY');status(`PASS — SHARED MASTER RESET VERIFIED: ${deleted} row(s) deleted, 0 remain.`,'ok');return deleted}
async function resetSharedScenario(){return clearEntireList()}
async function refreshScenario(){if(!sharedActive)throw new Error('Start Shared Scenario first.');requireToolDataColumn();let seed=lastSharedState||{environment:'SCENARIO TEST',tools:[]};await refreshAllItems();let tools=decodeSharedTools();if(!tools.length&&(seed.tools||[]).length){setFooterStatus(`SCENARIO TEST · SYNC WARNING · ${(seed.tools||[]).length} TOOLS RETAINED`);status('SYNC WARNING — List returned no valid tools. Last-known-good cards were retained.','err');return JSON.parse(JSON.stringify(seed))}let out=JSON.parse(JSON.stringify(seed));out.environment='SCENARIO TEST';out.tools=tools;lastSharedState=JSON.parse(JSON.stringify(out));updateFooter('SCENARIO TEST');status(`PASS — Refreshed ${tools.length} tool(s) from ${items.filter(isToolRow).length} Microsoft List tool row(s).`,'ok');return out}
async function enterScenario(localState){await ensureConnected();requireToolDataColumn();sharedActive=true;localStorage.setItem(SHARED_MODE_KEY,'1');let out=await loadSharedScenario(localState);updateFooter('SCENARIO TEST');status(`PASS — SHARED SCENARIO ACTIVE · ONE TOOL = ONE ROW · ${out.tools.length} tool(s).`,'ok');return out}
function leaveScenario(){sharedActive=false;localStorage.removeItem(SHARED_MODE_KEY);updateFooter('PRODUCTION')}
window.B7Shared={enterScenario,leaveScenario,queueStateSync,isActive:()=>sharedActive,updateFooter,resetSharedScenario,clearEntireList,refreshScenario,showActiveUsers,activeUsers,exportSharedBackup,restoreSharedBackup,replaceSharedScenario};

document.addEventListener('DOMContentLoaded',async()=>{inject();document.querySelector('#activeUsers')?.addEventListener('click',showActiveUsers);try{await initMsal();let resume=localStorage.getItem(SHARED_MODE_KEY)==='1';if(resume){setModeIdentity('shared','connecting');if(account){await connect();sharedActive=true;let seed={environment:'SCENARIO TEST',tools:[]};await refreshAllItems();let tools=decodeSharedTools();seed.tools=tools;lastSharedState=JSON.parse(JSON.stringify(seed));updateFooter('SCENARIO TEST');if(window.B7ApplySharedScenario)window.B7ApplySharedScenario(seed);status(`PASS — Multi-User session restored after refresh · ${tools.length} tool(s) loaded from Microsoft List.`,'ok')}else{updateFooter('SCENARIO TEST');status('MULTI-USER SESSION PAUSED — Sign in to reload shared tools from Microsoft List.','err')}}else{updateFooter('PRODUCTION');if(account)status('Existing Microsoft sign-in detected. Local data remains active until Shared Multi-User is started.','ok')}}catch(e){setModeIdentity('shared','offline');status('Authentication / shared restore warning — '+friendly(e),'err')}});
})();
