(()=>{'use strict';
const CFG={
  tenantId:'cf75356e-fe8e-498d-be4b-37ec8fbf04cf',
  clientId:'af82f005-0e21-4926-8d5d-8b6f872ab8f4',
  redirectUri:'http://localhost:5500/redirect.html',
  graph:'https://graph.microsoft.com/v1.0',
  siteHost:'kla-my.sharepoint.com',
  sitePath:'/personal/neptune_garcia_kla_com',
  listName:'B7 FI Command Center',
  scopes:['User.Read','Sites.ReadWrite.All']
};
let msalApp=null,account=null,site=null,list=null,columns=[],items=[],createdTestId=null;
const checks={signin:false,connect:false,read:false,write:false,readback:false,create:false,delete:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=(msg,kind='info')=>{let e=document.querySelector('#mu-status');if(e){e.className='mu-status '+kind;e.textContent=msg}};
function inject(){
 const style=document.createElement('style');style.textContent=`
 #mu-launch{position:fixed;right:18px;bottom:58px;z-index:2147483640;border:2px solid #54d8ff;background:#0b3150;color:#fff;font-weight:900;padding:10px 14px;border-radius:7px;cursor:pointer;box-shadow:0 0 18px #54d8ff55}
 #mu-panel{position:fixed;inset:4vh 4vw;z-index:2147483641;background:#08131f;color:#fff;border:2px solid #176fa8;border-radius:10px;box-shadow:0 20px 80px #000b;display:none;overflow:auto;padding:22px;font-family:Arial,sans-serif}
 body.presentation-mode #mu-launch,body.presentation-mode #mu-panel,body.presentation-mode #mu-panel *{pointer-events:auto!important}\n#mu-panel.open{display:block}.mu-head{display:flex;align-items:center;justify-content:space-between;gap:15px;border-bottom:2px solid #176fa8;padding-bottom:12px}.mu-head h2{margin:0}.mu-close{font-size:28px;background:none;border:0;color:#fff;cursor:pointer}.mu-status{margin:14px 0;padding:12px;border-radius:6px;background:#16283a}.mu-status.ok{background:#123d2b}.mu-status.err{background:#511c25}.mu-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.mu-btn{background:#176fa8;color:#fff;border:1px solid #54d8ff;padding:9px 12px;border-radius:5px;font-weight:800;cursor:pointer}.mu-btn:disabled{opacity:.4;cursor:not-allowed}.mu-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px;margin:12px 0}.mu-meta div{background:#101f2e;padding:9px;border-radius:5px}.mu-table{width:100%;border-collapse:collapse;margin-top:12px;font-size:13px}.mu-table th,.mu-table td{border:1px solid #2d4961;padding:7px;vertical-align:top}.mu-table th{background:#12314b;position:sticky;top:0}.mu-table input{width:100%;box-sizing:border-box;background:#0d1c29;color:#fff;border:1px solid #45647c;padding:6px}.mu-pass{color:#29e58c}.mu-warn{color:#ffd84a}.mu-note{font-size:12px;color:#b9ccda;line-height:1.4}.mu-user{font-weight:800;color:#54d8ff}.mu-checks{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:7px;margin:12px 0}.mu-check{background:#101f2e;border:1px solid #2d4961;border-radius:5px;padding:8px;font-weight:800}.mu-check.pass{border-color:#29e58c;color:#29e58c}`;document.head.appendChild(style);
 const b=document.createElement('button');b.id='mu-launch';b.textContent='MULTI-USER TEST';document.body.appendChild(b);
 const p=document.createElement('section');p.id='mu-panel';p.innerHTML=`<div class="mu-head"><div><h2>B7 FI COMMAND CENTER — MULTI-USER CONNECTION TEST</h2><div class="mu-note">V6.6.00 · Microsoft Entra delegated authentication · Microsoft Graph · Microsoft List</div></div><button class="mu-close" id="mu-close">×</button></div><div id="mu-status" class="mu-status">Ready. Start the Command Center at http://localhost:5500, then sign in.</div><div class="mu-meta"><div><b>USER</b><br><span id="mu-user">Not signed in</span></div><div><b>SITE</b><br>${esc(CFG.siteHost+CFG.sitePath)}</div><div><b>LIST</b><br>${esc(CFG.listName)}</div><div><b>MODE</b><br>Shared List Test</div></div><div class="mu-checks" id="mu-checks"></div><div class="mu-actions"><button class="mu-btn" id="mu-signin">1 · SIGN IN WITH KLA</button><button class="mu-btn" id="mu-connect" disabled>2 · CONNECT + READ</button><button class="mu-btn" id="mu-refresh" disabled>3 · REFRESH / FIND EXTERNAL ROW</button><button class="mu-btn" id="mu-create" disabled>4 · CREATE TEMP TEST ROW</button><button class="mu-btn" id="mu-delete" disabled>5 · DELETE TEMP TEST ROW</button><button class="mu-btn" id="mu-signout" disabled>SIGN OUT</button></div><p class="mu-note"><b>Purpose:</b> This build leaves the V6.5.96 Command Center data model unchanged. The panel below tests real multi-user read/write against the shared Microsoft List. Edit a test-row value and save it, then refresh from a second computer/user to verify shared updates. Saves use a change check to avoid silently overwriting a row changed by another user.</p><div id="mu-grid"></div>`;document.body.appendChild(p);
 b.onclick=()=>p.classList.add('open');p.querySelector('#mu-close').onclick=()=>p.classList.remove('open');
 p.querySelector('#mu-signin').onclick=signIn;p.querySelector('#mu-connect').onclick=connect;p.querySelector('#mu-refresh').onclick=loadItems;p.querySelector('#mu-create').onclick=createTempRow;p.querySelector('#mu-delete').onclick=deleteTempRow;p.querySelector('#mu-signout').onclick=signOut;renderChecks();
}
async function initMsal(){if(msalApp)return msalApp;if(!window.msal)throw new Error('Microsoft authentication library did not load. Check network access to cdn.jsdelivr.net.');msalApp=new msal.PublicClientApplication({auth:{clientId:CFG.clientId,authority:`https://login.microsoftonline.com/${CFG.tenantId}`,redirectUri:CFG.redirectUri},cache:{cacheLocation:'sessionStorage'}});await msalApp.initialize();account=msalApp.getAllAccounts()[0]||null;if(account)setSignedIn();return msalApp}
function setSignedIn(){document.querySelector('#mu-user').textContent=account?`${account.name||account.username} (${account.username})`:'Not signed in';document.querySelector('#mu-connect').disabled=!account;document.querySelector('#mu-refresh').disabled=!list;document.querySelector('#mu-create').disabled=!list;document.querySelector('#mu-delete').disabled=!createdTestId;document.querySelector('#mu-signout').disabled=!account}
function renderChecks(){let e=document.querySelector('#mu-checks');if(!e)return;let names={signin:'SIGN IN',connect:'LIST FOUND',read:'READ',write:'UPDATE',readback:'READ-BACK',create:'CREATE',delete:'CLEANUP'};e.innerHTML=Object.entries(names).map(([k,n])=>`<div class="mu-check ${checks[k]?'pass':''}">${checks[k]?'PASS':'WAIT'} · ${n}</div>`).join('')}
function pass(k){checks[k]=true;renderChecks()}
async function signIn(){try{await initMsal();let r=await msalApp.loginPopup({scopes:CFG.scopes,redirectUri:CFG.redirectUri});account=r.account;setSignedIn();pass('signin');status('PASS — KLA Microsoft sign-in succeeded.','ok')}catch(e){status('SIGN-IN FAILED — '+friendly(e),'err')}}
async function signOut(){try{if(msalApp&&account)await msalApp.logoutPopup({account,postLogoutRedirectUri:'http://localhost:5500/'});account=null;site=list=null;items=[];setSignedIn();document.querySelector('#mu-grid').innerHTML='';status('Signed out.')}catch(e){status('SIGN-OUT FAILED — '+friendly(e),'err')}}
async function token(){await initMsal();if(!account)throw new Error('Sign in first.');try{return (await msalApp.acquireTokenSilent({account,scopes:CFG.scopes})).accessToken}catch(e){return (await msalApp.acquireTokenPopup({account,scopes:CFG.scopes})).accessToken}}
async function graph(path,opt={}){let t=await token();let r=await fetch(CFG.graph+path,{...opt,headers:{Authorization:'Bearer '+t,'Content-Type':'application/json',...(opt.headers||{})}});let txt=await r.text(),data=null;try{data=txt?JSON.parse(txt):null}catch{}if(!r.ok){let msg=data?.error?.message||txt||`${r.status} ${r.statusText}`;throw new Error(`${r.status} — ${msg}`)}return data}
async function connect(){try{status('Connecting to Microsoft Graph…');site=await graph(`/sites/${CFG.siteHost}:${CFG.sitePath}`);let ls=await graph(`/sites/${encodeURIComponent(site.id)}/lists?$select=id,name,displayName`);list=ls.value.find(x=>(x.displayName||x.name||'').toLowerCase()===CFG.listName.toLowerCase());if(!list)throw new Error(`List “${CFG.listName}” was not found on the configured site.`);let cs=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/columns?$select=id,name,displayName,readOnly,hidden`);columns=(cs.value||[]).filter(c=>!c.hidden);pass('connect');status(`PASS — Connected to “${list.displayName||list.name}”. Reading shared test tools…`,'ok');document.querySelector('#mu-refresh').disabled=false;await loadItems()}catch(e){status('CONNECTION FAILED — '+friendly(e),'err')}}
async function loadItems(){try{if(!list)return connect();status('Refreshing shared Microsoft List data…');let d=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items?$expand=fields&$top=200`);items=d.value||[];renderGrid();pass('read');status(`PASS — Read ${items.length} shared list item${items.length===1?'':'s'}. If you add a third row directly in Microsoft Lists, press 3 · REFRESH and confirm it appears here.`, 'ok')}catch(e){status('READ FAILED — '+friendly(e),'err')}}
function fieldMap(){let m={};columns.forEach(c=>m[(c.displayName||c.name).trim().toLowerCase()]=c);return m}
function val(it,label){let c=fieldMap()[label.toLowerCase()];return c?it.fields?.[c.name]??'':''}
function editableColumns(){let wanted=['Title','UTID','Code Name','FI Status','Model','Customer','Sales Order','MFG Ship Date','Quarter','Family'],m=fieldMap();return wanted.map(x=>m[x.toLowerCase()]).filter(c=>c&&!c.readOnly)}
function renderGrid(){let g=document.querySelector('#mu-grid'),cols=editableColumns();if(!items.length){g.innerHTML='<p class="mu-warn">The list connected successfully but contains no items.</p>';return}g.innerHTML=`<table class="mu-table"><thead><tr>${cols.map(c=>`<th>${esc(c.displayName)}</th>`).join('')}<th>LAST MODIFIED</th><th>ACTION</th></tr></thead><tbody>${items.map(it=>`<tr data-mu-row="${esc(it.id)}">${cols.map(c=>`<td><input data-field="${esc(c.name)}" value="${esc(it.fields?.[c.name]??'')}"></td>`).join('')}<td>${esc(it.lastModifiedDateTime||'')}</td><td><button class="mu-btn" data-mu-save="${esc(it.id)}">SAVE SHARED ROW</button></td></tr>`).join('')}</tbody></table><p class="mu-note">Tip: for the first multi-user test, change only a harmless test value such as Customer on one of the two test tools. Save, then refresh on the second user's computer.</p>`;g.querySelectorAll('[data-mu-save]').forEach(b=>b.onclick=()=>saveRow(b.dataset.muSave))}
async function saveRow(id){try{let original=items.find(x=>x.id===id),row=document.querySelector(`[data-mu-row="${CSS.escape(id)}"]`);if(!original||!row)return;status(`Checking item ${id} for another user's changes…`);let current=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}?$expand=fields`);if(original.lastModifiedDateTime&&current.lastModifiedDateTime&&original.lastModifiedDateTime!==current.lastModifiedDateTime){status(`CONFLICT — Item ${id} changed after you loaded it. Your edit was NOT saved. Refresh shared data and review the other user's changes first.`,'err');return}let body={};row.querySelectorAll('[data-field]').forEach(i=>body[i.dataset.field]=i.value);await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}/fields`,{method:'PATCH',body:JSON.stringify(body)});pass('write');status(`PASS — Shared item ${id} saved. Reading it back now…`,`ok`);await loadItems();let verify=items.find(x=>x.id===id);if(verify){pass('readback');status(`PASS — UPDATE + READ-BACK verified for shared item ${id}.`,`ok`)}}catch(e){status('WRITE FAILED — '+friendly(e),'err')}}

async function createTempRow(){try{if(!list)return;status('Creating a temporary Microsoft List test row…');let cols=editableColumns(),body={};let title=cols.find(c=>(c.displayName||'').toLowerCase()==='title');if(title)body[title.name]='MULTI-USER TEST '+new Date().toISOString();let utid=cols.find(c=>(c.displayName||'').toLowerCase()==='utid');if(utid)body[utid.name]='MU-'+Date.now().toString().slice(-6);let r=await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items`,{method:'POST',body:JSON.stringify({fields:body})});createdTestId=String(r.id);pass('create');setSignedIn();status(`PASS — Created temporary shared row ${createdTestId}. It should now be visible directly in Microsoft Lists. Refreshing…`,'ok');await loadItems()}catch(e){status('CREATE FAILED — '+friendly(e),'err')}}
async function deleteTempRow(){try{if(!createdTestId)return;let id=createdTestId;status(`Deleting temporary test row ${id}…`);await graph(`/sites/${encodeURIComponent(site.id)}/lists/${encodeURIComponent(list.id)}/items/${encodeURIComponent(id)}`,{method:'DELETE'});createdTestId=null;pass('delete');setSignedIn();await loadItems();status(`PASS — Temporary row ${id} deleted. End-to-end CREATE/READ/UPDATE/DELETE test is complete.`,'ok')}catch(e){status('DELETE FAILED — '+friendly(e),'err')}}

function friendly(e){let s=e?.message||String(e);if(/AADSTS50011/i.test(s))return s+' Redirect URI mismatch: confirm http://localhost:5500/redirect.html is registered as SPA.';if(/403|accessDenied|insufficient/i.test(s))return s+' The signed-in user or Entra app may not have the required Microsoft Graph/List permission.';return s}
document.addEventListener('DOMContentLoaded',async()=>{inject();try{await initMsal();if(account)status('Existing Microsoft sign-in detected. You can connect to the shared List.','ok')}catch(e){status('Authentication setup warning — '+friendly(e),'err')}});
})();
