export const FAMILIES=['Panamera','Macan','Boxster','Taycan','Targa','Regera','Celestiq','Zephyr','Other'];
export const STATUSES=['OI','Waiting for FI','FI','Engineering','Powered Down','Packing','Shipped','Archived'];
export const BADGES=['Ironman','AV Data','SCC Cleanup','Backup','Customer Source','STR','WWC 1','WWC 2','WWC 3','Postmag','Foresight','OPK','Options Requested','Ship Kit Requested','Reduced Process','Verify Laser','Request Cal Chips','Verify Thermal Rack','System Wafers','FACTD','Options Testing','IMC Config','Powered Down','CTD Data','NCs','Ship Meeting','Customer','Sales Order'];
export const CHECKLISTS=['FI_130_010','FI_130_020','FI_140_010','FI_150_010','FI_150_020','FI_160_010','FI_160_020','FI_170_010','FI_170_020','FI_180_010','FI_190_010','FI_190_050','FI_200_90'];
export const LEAD_TASKS=['Issued system wafers','Notified planning team to transact wafers','Updated wafer log sheet','Requested lamp','Created test team chat','Request cal chips','Request DSW65F wafers','Create MFG options file','Customer source required','Request options','Verify loader','CTD data complete','Notify CA team','Ship meeting scheduled','Ship meeting completed','Request ship kit','Request POD','Create ship schedule'];
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const clean=s=>String(s??'').trim();
export function validTool(t){if(!t||typeof t!=='object'||Array.isArray(t)||t._recordType)return false;const id=clean(t.id||t.utid);if(!id||/^(A-|P-|B7ACTIVITY:|B7PRESENCE:)/i.test(id)||id.length>100)return false;return !!clean(t.codename||t.toolType||t.model||t.family)}
export function normalizeTool(t){const id=clean(t.id||t.utid);const type=clean(t.codename||t.toolType||t.family||'Other');const out={...t,id,codename:type,model:clean(t.model),customer:clean(t.customer),salesOrder:clean(t.salesOrder||t.so),driver:clean(t.driver),shipDate:clean(t.shipDate||t.ship),quarter:clean(t.quarter||'CY26Q4'),originalQuarter:clean(t.originalQuarter||t.quarter||'CY26Q4'),toolStatus:clean(t.toolStatus||t.status||'OI'),currentChecklist:clean(t.currentChecklist||t.checklist),microSchedule:clean(t.microSchedule),fiForecast:clean(t.fiForecast),latestStatus:clean(t.latestStatus),notes:clean(t.notes),priority:Math.max(0,Number(t.priority)||0),reducedProcess:!!t.reducedProcess,badges:{...(t.badges||{})},fiChecklistStates:{...(t.fiChecklistStates||{})},leadTasks:{...(t.leadTasks||{})},waferTracking:{...(t.waferTracking||{}),additional:{shiny:0,haze:0,dsw65:0,dsw65f:0,...(t.waferTracking?.additional||{})}},shipping:{...(t.shipping||{})},updatedAt:t.updatedAt||new Date().toISOString()};if(t.indicatorStates){for(const [key,value] of Object.entries(t.indicatorStates))if(!Object.hasOwn(out.badges,key))out.badges[key]=value}return out}
export function badgeValue(t,name){const map={'Options Requested':'options','Ship Kit Requested':'shipKit','System Wafers':'systemWafers','Reduced Process':'reducedProcess','Customer Source':'customerSource','AV Data':'avData','SCC Cleanup':'sccCleanup','Verify Laser':'laser','Request Cal Chips':'calChips','Verify Thermal Rack':'thermalRack','Options Testing':'completeOptions','IMC Config':'imcConfig','Powered Down':'poweredDown','Ship Meeting':'shipMeeting','CTD Data':'ctdData'};const k=map[name]||name.replace(/\W+/g,'').replace(/^./,x=>x.toLowerCase());return t.badges?.[name]??t.badges?.[k]??(name==='Reduced Process'?(t.reducedProcess?'Yes':'No'):'Not Started')}
export function isComplete(v){return /^(complete|done|yes|issued|passed|verified|requested|shipped|active)$/i.test(String(v||''))}
export function photo(t){const c=clean(t.codename).toLowerCase();if(c==='panamera')return 'assets/tool-293x.png';if(c==='macan')return 'assets/tool-2965.jpg';if(c==='boxster')return 'assets/tool-2915s2.png';if(c==='regera'||c==='celestiq')return 'assets/tool-regera-celestiq.png';if(c==='zephyr')return 'assets/tool-zephyr.png';return 'assets/tool-29xx-family.png'}
export function quarterOf(date=new Date()){return `CY${String(date.getFullYear()).slice(-2)}Q${Math.floor(date.getMonth()/3)+1}`}
