(()=>{'use strict';
const V8KEY='b7fi-command-center-v8-preview';
const V7PROD='b7fi-command-center-v3';
const VERSION='8.0.0-preview';
const centers=[['operations','⌂','OPERATIONS'],['shipping','▣','SHIPPING'],['priority','⚠','PRIORITY'],['status','▥','STATUS'],['cycle','◷','CYCLE TIME'],['meeting','♟','MEETING'],['action','✓','ACTION'],['reference','▣','REFERENCE'],['search','⌕','SEARCH'],['archive','▤','ARCHIVE']];
let route={center:'operations',sub:'live'};let state=loadState();let statusIndex=0;let toolIndex=0;let presentation={open:false,type:'summary',quarter:null,toolIndex:0};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date();
function activeQuarter(d=today()){return `CY${String(d.getFullYear()).slice(-2)}Q${Math.floor(d.getMonth()/3)+1}`}
function quarterBounds(q){let m=/CY(\d{2})Q([1-4])/.exec(q||'');if(!m)return null;let y=2000+Number(m[1]),qi=Number(m[2]);return{start:new Date(y,(qi-1)*3,1),end:new Date(y,qi*3,0),next:new Date(y,qi*3,1)}}
function qLabel(q){return q||activeQuarter()}
function daysBetween(a,b){if(!a||!b)return null;let x=new Date(a+'T12:00:00'),y=new Date(b+'T12:00:00');return Math.round((y-x)/86400000)}
function fmtDate(v){if(!v)return 'TBD';let d=new Date(v+'T12:00:00');return isNaN(d)?v:d.toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'2-digit'})}
function dateISO(d=today()){let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),da=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${da}`}
function normalizeTool(t,i=0){let q=t.originalQuarter||t.quarter||'CY26Q3';return{...t,id:String(t.id||t.utid||`TEST-${i+1}`),codename:t.codename||t.toolType||t.family||'BOXSTER',model:t.model||'2915S2',quarter:t.quarter||q,originalQuarter:q,customer:t.customer||'NO CUSTOMER',salesOrder:t.salesOrder||'NO SALES ORDER',driver:t.driver||'UNASSIGNED',toolStatus:t.toolStatus||'FI',currentChecklist:t.currentChecklist||'FI_130_010',shipDate:t.shipDate||'',fiHandoffDate:t.fiHandoffDate||'',microSchedule:t.microSchedule||'',nextForecastDate:t.nextForecastDate||'',leadProgress:Number(t.leadProgress||0),latestStatus:t.latestStatus||t.notes||'',archivedAt:t.archivedAt||'',shippedAt:t.shippedAt||'',shipping:t.shipping||{scheduleStatus:'Not Started',completed:{}},indicatorStates:t.indicatorStates||{},waferTracking:t.waferTracking||{additional:{shiny:0,haze:0,dsw65:0,dsw65f:0}}}}
function sampleState(){let families=['TARGA','BOXSTER','BOXSTER','BOXSTER','BOXSTER','BOXSTER','CELESTIQ','MACAN','PANAMERA','REGERA','REGERA','TARGA','TAYCAN','VANQUISH','ZEPHYR','BOXSTER','BOXSTER','BOXSTER','BOXSTER','BOXSTER'];let customers=['TSMC','KIOXIA','INTEL','SAMSUNG','MICRON','INFINEON','KIOXIA','MICRON','INFINEON','SONY','SAMSUNG','TSMC','PORSCHE','APPLE','MICRON'];let tools=families.map((f,i)=>normalizeTool({id:String(1350987+i),codename:f,model:i===0?'2955T':i%3===0?'2935I':'2915S2',customer:customers[i%customers.length],salesOrder:`SO-${String(i+1).padStart(2,'0')}`,driver:['Hao','Vinh','Daniel','Tony N','Allan','Hailey'][i%6],toolStatus:i<7?'Shipped':i<11?'Waiting FI':'FI',currentChecklist:i<7?'FI_200_90':i<11?'FI_130_010':i<15?'FI_150_010':'FI_160_010',shipDate:i===0?'2026-09-28':i<7?`2026-09-${String(22+i).padStart(2,'0')}`:`2026-10-${String((i-6)*2).padStart(2,'0')}`,fiHandoffDate:`2026-09-${String(10+i%12).padStart(2,'0')}`,leadProgress:i<7?100:(i*7)%65,originalQuarter:'CY26Q3',quarter:'CY26Q3',latestStatus:i===0?'Behind micro schedule · calibration NC open':'FI testing progressing'},i));return{version:VERSION,environment:'V8 PREVIEW',tools,actions:[{id:'a1',severity:'Critical',tool:'1350987',text:'Resolve calibration NC',owner:'Hao',due:'2026-09-26',status:'Open'},{id:'a2',severity:'High',tool:'1350995',text:'Confirm customer source',owner:'Daniel',due:'2026-09-27',status:'Open'},{id:'a3',severity:'Medium',tool:'1350999',text:'Check options arrival',owner:'Vinh',due:'2026-09-28',status:'Open'}],meetings:[],references:[],config:{plannedCount:20,quarterArchives:{}}}}
function loadState(){try{let v=JSON.parse(localStorage.getItem(V8KEY)||'null');if(v?.tools?.length)return normalizeState(v)}catch(e){}try{let v=JSON.parse(localStorage.getItem(V7PROD)||'null');if(v?.tools?.length){let copy=normalizeState(v);copy.environment='V8 SANDBOX COPY OF V7';localStorage.setItem(V8KEY,JSON.stringify(copy));return copy}}catch(e){}let s=sampleState();try{localStorage.setItem(V8KEY,JSON.stringify(s))}catch(e){}return s}
function normalizeState(s){return{...s,version:VERSION,tools:(s.tools||[]).map(normalizeTool),actions:s.actions||[],meetings:s.meetings||[],references:s.references||[],config:s.config||{}}}
function save(msg='SAVED'){try{localStorage.setItem(V8KEY,JSON.stringify(state))}catch(e){}toast(msg);render()}
function toolQuarter(t){return t.originalQuarter||t.quarter}
function isShipped(t){return t.toolStatus==='Shipped'||!!t.shippedAt}
function isArchived(t){return !!t.archivedAt}
function operationalTools(){let aq=activeQuarter();return state.tools.filter(t=>!isArchived(t)&&(toolQuarter(t)===aq||toolQuarter(t)<aq))}
function quarterTools(q){return state.tools.filter(t=>toolQuarter(t)===q&&!isArchived(t))}
function derive(t){let now=dateISO(),days=daysBetween(now,t.shipDate),cycle=t.fiHandoffDate?daysBetween(t.fiHandoffDate,isShipped(t)?(t.shippedAt?.slice(0,10)||t.shipDate||now):now):null;let progress=0;let m=/FI_(\d+)/.exec(t.currentChecklist||'');if(m)progress=Math.max(0,Math.min(100,(Number(m[1])-130)/.7));if(isShipped(t))progress=100;let behind=!isShipped(t)&&days!==null&&days<0;let attention=!isShipped(t)&&!behind&&days!==null&&days<=5;let carry=toolQuarter(t)<activeQuarter()&&!isArchived(t);return{days,cycle,progress:Math.round(progress),behind,attention,carry,status:isShipped(t)?'SHIPPED':behind?'BEHIND SCHEDULE':t.toolStatus==='Packing'?'PACKING':'ON SCHEDULE'}}
function photoFor(t){let c=(t.codename||'').toUpperCase();if(c==='REGERA'||c==='CELESTIQ')return'assets/tool-regera-celestiq.png';if(c==='ZEPHYR')return'assets/tool-zephyr.png';return'assets/tool-29xx-family.png'}
function countStatus(tools){let shipped=tools.filter(isShipped).length,packing=tools.filter(t=>t.toolStatus==='Packing').length,waiting=tools.filter(t=>/Waiting/i.test(t.toolStatus)).length,infi=Math.max(0,tools.length-shipped-packing-waiting);return{total:tools.length,shipped,packing,waiting,infi}}
function statusMessages(){let ops=operationalTools(),aq=activeQuarter(),qt=quarterTools(aq),c=countStatus(qt),oc=countStatus(ops),carry=ops.filter(t=>derive(t).carry&&!isShipped(t)),behind=ops.filter(t=>derive(t).behind),actions=(state.actions||[]).filter(a=>a.status!=='Complete');let qb=quarterBounds(aq),left=qb?daysBetween(dateISO(),dateISO(qb.end)):null;let msgs=[];if(carry.length)msgs.push({sev:'critical',title:'LEADS ALERT',sub:'CARRYOVER',text:`${carry.length} PRIOR-QUARTER CARRYOVER TOOL${carry.length===1?'':'S'} · SHIP ASAP`});else if(behind.length)msgs.push({sev:'critical',title:'LEADS ALERT',sub:'CRITICAL',text:`${behind.length} TOOL${behind.length===1?'':'S'} BEHIND SCHEDULE · ${actions.length} OPEN ACTIONS`});else msgs.push({sev:'good',title:'LEADS ALERT',sub:'CLEAR',text:`NO CRITICAL LEAD ESCALATIONS · ${actions.length} OPEN ACTIONS`});msgs.push({sev:left===0?'attention':'info',title:'SYSTEM STATUS',sub:left===0?'FINAL DAY':'LIVE FLEET',text:left===0?`${aq} FINAL DAY · ${c.total-c.shipped} TOOLS LEFT TO SHIP`:`${oc.waiting} WAITING FI · ${oc.infi} IN FI · ${oc.packing} PACKING · ${oc.shipped} SHIPPED`});msgs.push({sev:carry.length?'critical':left===0?'critical':'info',title:'COMMAND CENTER',sub:carry.length?'CARRYOVER':left===0?'FINAL DAY':'BRAIN',text:carry.length?`${aq} ACTIVE · ${carry.length} CARRYOVER · ${carry.map(t=>t.id).slice(0,3).join(' · ')}`:left===0?`${aq} QUARTER ENDS TODAY · ${c.shipped} OF ${c.total} SHIPPED`:`${aq} ACTIVE · ${c.shipped} OF ${c.total} SHIPPED · ${c.total-c.shipped} REMAINING`});return msgs}
function renderStatusBars(){let base=statusMessages(),rot=base.map((_,i)=>base[(i+statusIndex)%base.length]);$('#statusBars').innerHTML=rot.map((m,i)=>`<div class="status-bar ${m.sev} ${i===2?'command':''}"><div class="status-lamp"></div><div class="status-title">${m.title}<small>${m.sub}</small></div><div class="status-message">${esc(m.text)}</div><div class="status-open">OPEN →</div></div>`).join('')}
function renderHeader(){let aq=activeQuarter();$('#headerQuarter').textContent=aq;$('#footerQuarter').textContent=aq;$('#clockText').textContent=today().toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).toUpperCase();$('#modeText').textContent=state.environment||'V8 PREVIEW MODE';$('#connectionText').textContent='SANDBOX · V7 DATA SAFE';renderStatusBars();$('#mainNav').innerHTML=centers.map(([id,ic,n])=>`<button class="nav-btn ${route.center===id?'active':''}" data-center="${id}">${ic} &nbsp; ${n}</button>`).join('');renderSubNav()}
function renderSubNav(){let defs={operations:[['live','LIVE OPERATIONS'],['summary',`${activeQuarter()} SUMMARY`],['tools','TOOLS'],['daily','DAILY STATUS']],shipping:[['home','SHIPPING CENTER']],priority:[['home','SYSTEM PRIORITIES']],status:[['home','DAILY STATUS']],cycle:[['home','CYCLE TIME']],meeting:[['home','MORNING MEETING']],action:[['home','ACTION CENTER']],reference:[['home','REFERENCE CENTER']],search:[['home','SEARCH CENTER']],archive:[['home','ARCHIVE CENTER']]};let arr=defs[route.center]||[];$('#subNav').innerHTML=arr.map(([id,n])=>`<button class="sub-btn ${route.sub===id?'active':''}" data-sub="${id}">${n}</button>`).join('')+`<span class="sub-spacer"></span><button class="action-btn" data-presentation="summary">▣ PRESENTATION</button><button class="action-btn" data-screenshot>SCREENSHOT</button>`}
function meter(p){return`<div class="meter"><i style="width:${Math.max(0,Math.min(100,p))}%"></i></div>`}
function quarterPulse(q){let tools=quarterTools(q),c=countStatus(tools),b=quarterBounds(q),left=b?Math.max(0,daysBetween(dateISO(),dateISO(b.end))):0;let fam=[...new Set(tools.map(t=>t.codename))];return`<section class="panel"><div class="panel-title">${q} QUARTER PULSE <small>LIVE</small></div><div class="quarter-pulse"><div class="kpi red"><h3>TOOLS LEFT TO SHIP</h3><strong>${c.total-c.shipped}</strong>${meter(c.total?c.shipped/c.total*100:0)}<small>${c.shipped} OF ${c.total} SHIPPED</small></div><div class="kpi yellow"><h3>${left===0?'FINAL DAY':'DAYS REMAINING'}</h3><strong>${left===0?'!':left}</strong>${meter(b?Math.max(0,Math.min(100,100-left/92*100)):0)}<small>${left===0?'QUARTER ENDS TODAY':q}</small></div></div><div class="family-bars">${fam.map(f=>{let a=tools.filter(t=>t.codename===f),s=a.filter(isShipped).length;return`<div class="family-row"><span>${esc(f)}</span><div class="bar"><i style="width:${a.length?s/a.length*100:0}%"></i></div><b>${s} / ${a.length}</b></div>`}).join('')}</div></section>`}
function fleetKpis(tools){let c=countStatus(tools);return`<div class="fleet-kpis"><div class="mini-kpi"><small>TOTAL</small><strong>${c.total}</strong></div><div class="mini-kpi"><small>PULLED IN</small><strong>0</strong></div><div class="mini-kpi"><small>PUSHED OUT</small><strong>0</strong></div><div class="mini-kpi"><small>UPDATED</small><strong>${c.total}</strong></div><div class="mini-kpi waiting"><small>WAITING FI</small><strong>${c.waiting}</strong></div><div class="mini-kpi infi"><small>IN FI</small><strong>${c.infi}</strong></div><div class="mini-kpi"><small>PACKING</small><strong>${c.packing}</strong></div><div class="mini-kpi shipped"><small>SHIPPED</small><strong>${c.shipped}</strong></div></div>`}
function miniTool(t,i){let d=derive(t);return`<div class="mini-tool ${d.behind?'behind':''}" data-tool="${esc(t.id)}"><img src="${photoFor(t)}"><b>#${i+1} ${esc(t.codename)}</b><small>${esc(t.model)} · ${esc(t.id)}</small><em>${d.status}${d.days!==null&&!isShipped(t)?` · ${Math.abs(d.days)} DAYS${d.days<0?' OVERDUE':''}`:''}</em></div>`}
function liveStatus(tools){let five=tools.slice(toolIndex,toolIndex+5);if(five.length<5)five=[...five,...tools.slice(0,5-five.length)];return`<section class="panel"><div class="panel-title">LIVE OPERATIONAL FLEET <small>${activeQuarter()} + CARRYOVER</small></div><div class="live-status">${fleetKpis(tools)}<div class="mini-tool-strip">${five.map(miniTool).join('')}</div></div></section>`}
function toolCard(t,i){let d=derive(t),cls=d.behind?'behind':d.attention?'attn':isShipped(t)?'shipped':'';let dayText=isShipped(t)?'SHIPPED':d.days===null?'NO DATE':d.days<0?`${Math.abs(d.days)} DAYS OVERDUE`:`${d.days} DAYS`;return`<article class="tool-card ${cls}" data-tool="${esc(t.id)}"><div class="tool-head"><div class="tool-priority">#${i+1}</div><b>${esc(t.codename)}</b><span>${d.status}</span></div><div class="tool-body"><img class="tool-photo" src="${photoFor(t)}"><div class="tool-metrics"><div class="metric"><small>SHIP COUNTDOWN</small><b>${dayText}</b></div><div class="metric"><small>FI PROGRESS</small><b>${d.progress}%</b></div><div class="metric"><small>MICRO SCHEDULE</small><b>${Math.min(100,d.progress+12)}%</b></div><div class="metric"><small>CYCLE TIME</small><b>${d.cycle??'—'} / 25</b></div><div class="metric"><small>PACKING</small><b>${isShipped(t)?'100':'0'}%</b></div></div></div><div class="tool-info"><div><span>UTID</span><b>${esc(t.id)}</b></div><div><span>MODEL</span><b>${esc(t.model)}</b></div><div><span>CUSTOMER</span><b>${esc(t.customer)}</b></div><div><span>SALES ORDER</span><b>${esc(t.salesOrder)}</b></div><div><span>DRIVER</span><b class="driver">${esc(t.driver)}</b></div>${d.carry?`<div style="display:block;background:#67101f;border:1px solid #ff315b;padding:5px;text-align:center;font-weight:900;color:#ff8ba1">⚠ QUARTER CARRYOVER · SHIP ASAP</div>`:''}<div><span>BADGES</span><div class="badge-preview">${Array.from({length:6},()=>'<i></i>').join('')}<b>+22</b></div></div></div><button class="tool-action" data-edit-tool="${esc(t.id)}">UPDATE TOOL STATUS →</button></article>`}
function operationsLive(){let tools=operationalTools();return`<div class="grid ops-top">${quarterPulse(activeQuarter())}${liveStatus(tools)}</div><section class="panel carousel-panel"><div class="panel-title"><span>TOOL CAROUSEL — ACTIVE FLEET</span><div class="carousel-toolbar"><button class="btn" data-carousel="prev">◀</button><button class="btn" data-carousel="next">▶</button><button class="btn" data-presentation="tools">▣ PRESENT</button></div></div><div class="tool-carousel">${tools.slice(toolIndex,toolIndex+5).concat(tools.slice(0,Math.max(0,5-tools.slice(toolIndex).length))).map(toolCard).join('')}</div></section>`}
function summaryComponent(q){let tools=quarterTools(q),c=countStatus(tools),b=quarterBounds(q),left=b?daysBetween(dateISO(),dateISO(b.end)):0,final=left===0,ended=left<0;let fam=[...new Set(tools.map(t=>t.codename))];let dayOf=b?Math.min(92,Math.max(1,daysBetween(dateISO(b.start),dateISO())+1)):0;return`<div class="summary-shell" data-summary-component="${q}"><div class="summary-hero"><div class="kpi red"><h3>${q} TOOLS LEFT TO SHIP</h3><strong>${Math.max(0,c.total-c.shipped)}</strong>${meter(c.total?c.shipped/c.total*100:0)}<small>${c.shipped} OF ${c.total} TOOLS SHIPPED &nbsp; | &nbsp; ${Math.max(0,c.total-c.shipped)} TOOLS LEFT</small></div><div class="kpi ${final||ended?'red':'yellow'}"><h3>${q} ${ended?'QUARTER ENDED':final?'LAST DAY OF THE QUARTER':'QUARTER COUNTDOWN'}</h3><strong>${ended?'ENDED':final?'FINAL DAY':Math.max(0,left)+' DAYS'}</strong>${meter(b?Math.max(0,Math.min(100,dayOf/92*100)):0)}<small>${ended?'FINAL CLOSE':`DAY ${dayOf} OF 92 &nbsp; | &nbsp; ${final?'QUARTER ENDS TODAY':left+' DAYS REMAINING'}`}</small></div></div>${fleetKpis(tools)}<div class="panel summary-family"><div class="summary-table"><div class="summary-cell">SYSTEM</div><div class="summary-cell">TOTAL</div><div class="summary-cell">WAITING FI</div><div class="summary-cell">IN FI</div><div class="summary-cell">PACKING</div><div class="summary-cell">SHIPPED</div><div class="summary-cell">SHIPPING PROGRESS</div><div class="summary-cell">REVEAL</div>${fam.map(f=>{let a=tools.filter(t=>t.codename===f),s=a.filter(isShipped).length,cc=countStatus(a);return`<div class="summary-cell name"><b>${esc(f)}</b><div class="tool-icons">${a.map(t=>`<span class="tool-icon ${isShipped(t)?'shipped':''}" data-tool="${esc(t.id)}"><img src="${photoFor(t)}"></span>`).join('')}</div></div><div class="summary-cell">${a.length}</div><div class="summary-cell waiting">${cc.waiting}</div><div class="summary-cell infi">${cc.infi}</div><div class="summary-cell packing">${cc.packing}</div><div class="summary-cell shipped">${cc.shipped}</div><div class="summary-cell progress-cell"><i style="width:${a.length?s/a.length*100:0}%"></i><span>${s} OF ${a.length} SHIPPED</span></div><div class="summary-cell reveal ${s===a.length?'open':''}">${s===a.length?'🎁':'🔒'}</div>`}).join('')}</div></div></div>`}
function dataTable(tools,kind='daily'){let rows=tools.map((t,i)=>{let d=derive(t);return`<tr data-tool="${esc(t.id)}"><td>${kind==='priority'?`<span class="priority-num">${i+1}</span>`:i+1}</td><td>${esc(t.id)}</td><td>${esc(t.codename)}</td><td>${esc(t.model)}</td><td>${esc(t.customer)}</td><td><span class="pill ${d.behind?'red':isShipped(t)?'green':d.attention?'yellow':'blue'}">${d.status}</span></td><td>${esc(t.currentChecklist)}</td><td>${fmtDate(t.shipDate)}</td><td>${d.days===null?'—':d.days}</td><td><button class="btn" data-edit-tool="${esc(t.id)}">OPEN</button></td></tr>`}).join('');return`<div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>UTID</th><th>TOOL TYPE</th><th>MODEL</th><th>CUSTOMER</th><th>STATUS</th><th>CURRENT STEP</th><th>SHIP DATE</th><th>DAYS</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`}
function toolsPage(){let tools=operationalTools();return`<section class="panel"><div class="panel-title">${activeQuarter()} TOOLS <small>${tools.length} ACTIVE / CARRYOVER</small></div><div class="tool-carousel" style="grid-template-columns:repeat(auto-fit,minmax(260px,1fr));overflow:visible">${tools.map(toolCard).join('')}</div></section>`}
function shippingPage(){let tools=operationalTools();return`<h1 class="page-title">SHIPPING CENTER — ${activeQuarter()}</h1><section class="panel data-panel"><div class="toolbar"><button class="btn primary">ALL</button><button class="btn">FI TESTING</button><button class="btn">PACKING</button><button class="btn">READY TO SHIP</button><button class="btn">SHIPPED</button></div>${dataTable(tools)}</section>`}
function priorityPage(){let tools=operationalTools().slice().sort((a,b)=>Number(derive(b).behind)-Number(derive(a).behind)||(derive(a).days??999)-(derive(b).days??999));return`<h1 class="page-title">SYSTEM PRIORITIES — ${activeQuarter()}</h1><section class="panel data-panel"><div class="toolbar"><button class="btn primary">ALL TOOLS</button><button class="btn">HIGHEST PRIORITY</button><button class="btn">BEHIND SCHEDULE</button><button class="btn">CRITICAL NCs</button><button class="btn">CUSTOMER SOURCE</button></div>${dataTable(tools,'priority')}</section>`}
function statusPage(){return`<h1 class="page-title">STATUS CENTER — DAILY STATUS</h1><section class="panel data-panel"><div class="toolbar"><button class="btn primary">DAILY STATUS</button><button class="btn">UPDATE COMMAND CENTER</button><span style="flex:1"></span><button class="btn">ALL TOOLS</button></div>${dataTable(operationalTools())}</section>`}
function cyclePage(){let tools=operationalTools();let vals=tools.map(t=>derive(t).cycle||0);return`<h1 class="page-title">CYCLE TIME CENTER</h1><div class="chart-grid"><section class="panel chart"><div class="panel-title">FI CYCLE TIME (DAYS)</div><div class="bars">${tools.slice(0,8).map((t,i)=>`<div class="bar-col"><i style="height:${Math.min(100,(vals[i]||8)/30*100)}%"></i><b>${esc(t.codename)}</b><small>${vals[i]||'—'}</small></div>`).join('')}</div></section><section class="panel chart"><div class="panel-title">CYCLE TIME TREND</div><div class="line-chart"><svg viewBox="0 0 500 180" preserveAspectRatio="none"><polyline fill="none" stroke="#12c9ff" stroke-width="4" points="0,130 60,110 120,120 180,75 240,90 300,55 360,70 420,45 500,60"/><polyline fill="none" stroke="#ff315b" stroke-width="3" points="0,105 60,100 120,92 180,95 240,80 300,84 360,68 420,75 500,48"/></svg></div></section></div><section class="panel data-panel" style="margin-top:10px">${dataTable(tools)}</section>`}
function meetingPage(){let tools=operationalTools().slice(0,7),actions=(state.actions||[]).filter(a=>a.status!=='Complete');return`<h1 class="page-title">MEETING CENTER — MORNING MEETING</h1><div class="meeting-grid"><section class="panel note-box"><h3>TODAY'S PRIORITIES</h3><ol>${tools.slice(0,5).map(t=>`<li><b>${esc(t.codename)}</b> — ${esc(derive(t).status)} · ${esc(t.currentChecklist)}</li>`).join('')}</ol></section><section class="panel note-box"><h3>MEETING NOTES</h3><ul><li>TARGA — confirm customer source requirements.</li><li>BOXSTER — calibration NC in progress.</li><li>CELESTIQ — packing handoff follow-up.</li><li>MACAN — waiting for CTD data.</li></ul><button class="btn primary">ADD NOTE</button></section><section class="panel note-box"><h3>ACTION ITEMS</h3>${actions.map(a=>`<div style="padding:7px;border-bottom:1px solid #123149"><b>${esc(a.tool)}</b> · ${esc(a.text)}<br><small>${esc(a.owner)} · ${fmtDate(a.due)}</small></div>`).join('')}<button class="btn primary" style="margin-top:10px">ADD ACTION</button></section></div>`}
function actionPage(){let acts=state.actions||[];return`<h1 class="page-title">ACTION CENTER</h1><section class="panel data-panel"><div class="toolbar"><button class="btn primary">OPEN ACTIONS</button><button class="btn">ALL ACTIONS</button><button class="btn">ESCALATIONS</button></div>${acts.map(a=>`<div class="action-card"><span class="pill ${a.severity==='Critical'?'red':a.severity==='High'?'yellow':'blue'}">${esc(a.severity)}</span><b>${esc(a.tool)}</b><span>${esc(a.text)}</span><span>${esc(a.owner)}</span></div>`).join('')}</section>`}
function referencePage(){let refs=[['📁','FILE MANAGER','Network & local files'],['🔗','QUICK LINKS','UTID lookup · SharePoint · Options'],['👥','DRIVER ROSTER','29 drivers'],['▦','TOOL TYPES','FI families'],['▣','TEMPLATES','NC forms · meeting templates'],['🛠','GUIDES','FI checklist guides']];return`<h1 class="page-title">REFERENCE CENTER</h1><div class="reference-grid">${refs.map(r=>`<section class="panel ref-card"><span>${r[0]}</span><strong>${r[1]}</strong><small>${r[2]}</small></section>`).join('')}</div>`}
function searchPage(){return`<h1 class="page-title">SEARCH CENTER</h1><section class="panel data-panel"><div class="toolbar"><input id="searchInput" placeholder="Search by UTID, model, customer, driver, status..."><button class="btn primary" data-run-search>SEARCH</button></div><div id="searchResults">${dataTable(operationalTools())}</div></section>`}
function archivePage(){let qs=[...new Set(state.tools.map(toolQuarter))].sort();return`<h1 class="page-title">ARCHIVE CENTER</h1><div class="archive-grid">${qs.map(q=>{let a=state.tools.filter(t=>toolQuarter(t)===q),s=a.filter(isShipped).length;return`<section class="panel archive-card"><small>${q} SUMMARY</small><h2>${s} OF ${a.length} SHIPPED</h2>${meter(a.length?s/a.length*100:0)}<p>${a.length?Math.round(s/a.length*100):0}% COMPLETION</p><button class="btn primary" data-summary-quarter="${q}">VIEW QUARTER SUMMARY</button></section>`}).join('')}</div>`}
function adminPage(){return`<h1 class="page-title">ADMINISTRATION CENTER — V8 PREVIEW</h1><div class="notice"><b>SAFE PREVIEW MODE:</b> V8 writes only to its own browser storage. Your V7 production data is not modified.</div><div class="admin-grid"><section class="panel admin-card"><h2>DATA</h2><p>Current sandbox: <b>${esc(state.environment)}</b></p><p>Tools loaded: <b>${state.tools.length}</b></p><button class="btn primary" data-import-v7>RE-IMPORT CURRENT V7 PRODUCTION DATA</button> <button class="btn danger" data-load-demo>LOAD V8 DEMO DATA</button></section><section class="panel admin-card"><h2>V8 FOUNDATION</h2><p>One application shell · one Tool Card component · one Quarter Summary component · no V7 CSS loaded.</p><p>Browser zoom uses responsive layout instead of whole-app scaling.</p><button class="btn" data-presentation="summary">OPEN PRESENTATION MODE</button></section></div>`}
function renderPage(){let html='';if(route.center==='operations'){if(route.sub==='summary')html=summaryComponent(activeQuarter());else if(route.sub==='tools')html=toolsPage();else if(route.sub==='daily')html=statusPage();else html=operationsLive()}else if(route.center==='shipping')html=shippingPage();else if(route.center==='priority')html=priorityPage();else if(route.center==='status')html=statusPage();else if(route.center==='cycle')html=cyclePage();else if(route.center==='meeting')html=meetingPage();else if(route.center==='action')html=actionPage();else if(route.center==='reference')html=referencePage();else if(route.center==='search')html=searchPage();else if(route.center==='archive')html=archivePage();else if(route.center==='admin')html=adminPage();$('#workspace').innerHTML=html}
function render(){renderHeader();renderPage();if(presentation.open)renderPresentation()}
function openTool(id){let t=state.tools.find(x=>x.id===id);if(!t)return;let d=derive(t);$('#modalBody').innerHTML=`<h1>${esc(t.id)} · ${esc(t.codename)} · ${esc(t.model)}</h1><p><span class="pill ${d.behind?'red':isShipped(t)?'green':'blue'}">${d.status}</span>${d.carry?' <span class="pill red">QUARTER CARRYOVER · SHIP ASAP</span>':''}</p><div class="edit-grid">${field('UTID','id',t.id)}${field('Tool Type','codename',t.codename)}${field('Model','model',t.model)}${field('Customer','customer',t.customer)}${field('Sales Order','salesOrder',t.salesOrder)}${field('Driver','driver',t.driver)}${field('Ship Date','shipDate',t.shipDate,'date')}${field('Tool Status','toolStatus',t.toolStatus)}${field('Current Checklist','currentChecklist',t.currentChecklist)}<div class="field span3"><label>LATEST STATUS / NOTES</label><textarea data-field="latestStatus">${esc(t.latestStatus)}</textarea></div></div><div style="margin-top:15px"><button class="btn primary" data-save-tool="${esc(t.id)}">SAVE CHANGES</button> <button class="btn" data-close-modal>CANCEL</button></div>`;$('#modal').classList.remove('hidden')}
function field(label,key,val,type='text'){return`<div class="field"><label>${label}</label><input type="${type}" data-field="${key}" value="${esc(val)}"></div>`}
function closeModal(){$('#modal').classList.add('hidden')}
function renderPresentation(){let q=presentation.quarter||activeQuarter(),tools=operationalTools(),t=tools[presentation.toolIndex%Math.max(1,tools.length)];let content=presentation.type==='tools'&&t?`<div style="height:100%;padding:10px;display:grid;place-items:center"><div style="width:min(1500px,95vw)">${toolCard(t,presentation.toolIndex+1)}</div></div>`:summaryComponent(q);$('#presentation').innerHTML=`<div class="presentation-content">${content}</div><div class="presentation-nav"><button data-pres-tools class="${presentation.type==='tools'?'active':''}">${qLabel(activeQuarter())} TOOLS</button><button data-pres-summary="CY26Q3" class="${presentation.type==='summary'&&q==='CY26Q3'?'active':''}">CY26Q3 QUARTER SUMMARY</button><button data-pres-summary="CY26Q4" class="${presentation.type==='summary'&&q==='CY26Q4'?'active':''}">CY26Q4 QUARTER SUMMARY</button><button data-pres-prev>◀ PREVIOUS / NEXT ▶</button><button data-pres-exit>ESC TO EXIT</button></div>`;$('#presentation').classList.remove('hidden')}
function toast(s){let el=$('#toast');el.textContent=s;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function runSearch(){let q=($('#searchInput')?.value||'').trim().toLowerCase();let tools=state.tools.filter(t=>!q||Object.values(t).some(v=>typeof v==='string'&&v.toLowerCase().includes(q)));$('#searchResults').innerHTML=dataTable(tools)}
document.addEventListener('click',e=>{let b=e.target.closest('button,[data-tool],[data-summary-quarter]');if(!b)return;if(b.dataset.center){route={center:b.dataset.center,sub:b.dataset.center==='operations'?'live':'home'};render();return}if(b.dataset.sub){route.sub=b.dataset.sub;render();return}if(b.id==='adminBtn'){route={center:'admin',sub:'home'};render();return}if(b.dataset.tool){openTool(b.dataset.tool);return}if(b.dataset.editTool){openTool(b.dataset.editTool);return}if(b.hasAttribute('data-close-modal')){closeModal();return}if(b.dataset.saveTool){let t=state.tools.find(x=>x.id===b.dataset.saveTool);if(t){$$('#modal [data-field]').forEach(el=>t[el.dataset.field]=el.value);save('TOOL UPDATED IN V8 SANDBOX');closeModal()}return}if(b.dataset.carousel){let tools=operationalTools();toolIndex=(toolIndex+(b.dataset.carousel==='next'?5:-5)+Math.max(1,tools.length))%Math.max(1,tools.length);render();return}if(b.dataset.presentation){presentation={open:true,type:b.dataset.presentation,quarter:activeQuarter(),toolIndex:0};renderPresentation();return}if(b.dataset.presSummary){presentation.type='summary';presentation.quarter=b.dataset.presSummary;renderPresentation();return}if(b.hasAttribute('data-pres-tools')){presentation.type='tools';renderPresentation();return}if(b.hasAttribute('data-pres-prev')){if(presentation.type==='tools')presentation.toolIndex=(presentation.toolIndex+1)%Math.max(1,operationalTools().length);else presentation.quarter=presentation.quarter==='CY26Q3'?'CY26Q4':'CY26Q3';renderPresentation();return}if(b.hasAttribute('data-pres-exit')){presentation.open=false;$('#presentation').classList.add('hidden');return}if(b.dataset.summaryQuarter){route={center:'operations',sub:'summary'};render();return}if(b.hasAttribute('data-run-search')){runSearch();return}if(b.hasAttribute('data-import-v7')){try{let v=JSON.parse(localStorage.getItem(V7PROD)||'null');if(!v?.tools?.length)return alert('No V7 production data was found in this browser.');state=normalizeState(v);state.environment='V8 SANDBOX COPY OF V7';localStorage.setItem(V8KEY,JSON.stringify(state));toast('V7 DATA COPIED INTO V8 SANDBOX');render()}catch(err){alert(err.message)}return}if(b.hasAttribute('data-load-demo')){if(confirm('Replace only the V8 sandbox with demo data? V7 will not be changed.')){state=sampleState();save('V8 DEMO DATA LOADED')}return}if(b.hasAttribute('data-screenshot')){document.documentElement.requestFullscreen?.();return}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&presentation.open){presentation.open=false;$('#presentation').classList.add('hidden')}if(e.key==='Escape'&&!$('#modal').classList.contains('hidden'))closeModal()});
setInterval(()=>{statusIndex=(statusIndex+1)%3;renderStatusBars()},8000);setInterval(()=>{let c=$('#clockText');if(c)c.textContent=today().toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).toUpperCase()},30000);
render();
})();
