(()=>{'use strict';
const V8KEY='b7fi-command-center-v8-full-preview';
const V8PREVIEW='b7fi-command-center-v8-preview';
const V7PROD='b7fi-command-center-v3';
const VERSION='8.1.0-full-preview';
const centers=[['operations','⌂','OPERATIONS'],['shipping','▣','SHIPPING'],['priority','⚠','PRIORITY'],['status','▥','STATUS'],['cycle','◷','CYCLE TIME'],['meeting','♟','MEETING'],['action','✓','ACTION'],['reference','▣','REFERENCE'],['search','⌕','SEARCH'],['archive','▤','ARCHIVE']];
let route={center:'operations',sub:'live'};let state=loadState();let statusIndex=0;let toolIndex=0;let presentation={open:false,type:'summary',quarter:null,toolIndex:0};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date();
function activeQuarter(d=today()){return `CY${String(d.getFullYear()).slice(-2)}Q${Math.floor(d.getMonth()/3)+1}`}
function quarterBounds(q){let m=/CY(\d{2})Q([1-4])/.exec(q||'');if(!m)return null;let y=2000+Number(m[1]),qi=Number(m[2]);return{start:new Date(y,(qi-1)*3,1),end:new Date(y,qi*3,0),next:new Date(y,qi*3,1)}}
function qLabel(q){return q||activeQuarter()}
function daysBetween(a,b){if(!a||!b)return null;let x=new Date(a+'T12:00:00'),y=new Date(b+'T12:00:00');return Math.round((y-x)/86400000)}
function fmtDate(v){if(!v)return 'TBD';let d=new Date(v+'T12:00:00');return isNaN(d)?v:d.toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'2-digit'})}
function dateISO(d=today()){let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),da=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${da}`}
function normalizeTool(t,i=0){
  let q=t.originalQuarter||t.quarter||'CY26Q3';
  const badgeNames=['Options Requested','Ship Kit Requested','Ironman','SCC Cleanup','Backup','CTD Data','Customer Source Required','Verify Loader','Postmag','OPK','Options Testing','Verify Thermal Rack','Verify Laser','Lamp Hours','AV Data','CCL','STR Required','WWC Required','IMC Config','System Powered','Ship Meeting','Request Cal Chips','System Wafers','NC','EQ Checklists','Verify Chiller','Option Files','Request POD'];
  let badges={}; badgeNames.forEach(n=>badges[n]=(t.badges&&t.badges[n])||(t.indicatorStates&&t.indicatorStates[n])||'Required');
  let add=t.waferTracking?.additional||{};
  return {...t,
    id:String(t.id||t.utid||`TEST-${i+1}`),codename:t.codename||t.toolType||t.family||'BOXSTER',model:t.model||'2915S2',quarter:t.quarter||q,originalQuarter:q,
    customer:t.customer||'NO CUSTOMER',salesOrder:t.salesOrder||'NO SALES ORDER',driver:t.driver||'UNASSIGNED',priority:Number(t.priority||i+1),reducedProcess:!!t.reducedProcess,
    toolStatus:t.toolStatus||'FI',currentChecklist:t.currentChecklist||'FI_130_010',currentLeadTask:t.currentLeadTask||'',currentSystemStatus:t.currentSystemStatus||t.toolStatus||'FI TESTING',
    nextSystemTasks:Array.isArray(t.nextSystemTasks)?t.nextSystemTasks:['Review next FI checklist','Verify open requirements','Confirm schedule'],
    shipDate:t.shipDate||'',fiHandoffDate:t.fiHandoffDate||'',microSchedule:t.microSchedule||'',nextForecastDate:t.nextForecastDate||'',fiForecast:t.fiForecast||'',cycleTarget:Number(t.cycleTarget||25),leadProgress:Number(t.leadProgress||0),
    latestStatus:t.latestStatus||t.notes||'',leadNotes:t.leadNotes||'',archivedAt:t.archivedAt||'',shippedAt:t.shippedAt||'',
    shipping:{scheduleStatus:t.shipping?.scheduleStatus||'Not Started',completed:{subsystems:!!t.shipping?.completed?.subsystems,accessories:!!t.shipping?.completed?.accessories,cables:!!t.shipping?.completed?.cables,mat:!!t.shipping?.completed?.mat,is:!!t.shipping?.completed?.is}},
    customerSource:{required:t.customerSource?.required||'TBD',preSource:t.customerSource?.preSource||'Not Started',caHandoff:t.customerSource?.caHandoff||'Not Started',sourceStart:t.customerSource?.sourceStart||'',sourceComplete:t.customerSource?.sourceComplete||''},
    str:{required:t.str?.required||'TBD',requirements:t.str?.requirements||'Not Received',testing:t.str?.testing||'Not Started',complete:t.str?.complete||''},
    requests:{options:t.requests?.options||'Need to Request',lamp:t.requests?.lamp||'TBD',specialWafers:t.requests?.specialWafers||'None',calChips:t.requests?.calChips||'Need to Request',missingOptions:t.requests?.missingOptions||''},
    optionsFiles:{manufacturing:t.optionsFiles?.manufacturing||'TBD',material:t.optionsFiles?.material||'TBD',impact:t.optionsFiles?.impact||'TBD',install:t.optionsFiles?.install||'TBD',rc:t.optionsFiles?.rc||'TBD',customer:t.optionsFiles?.customer||'TBD'},
    badges,indicatorStates:t.indicatorStates||{},
    waferTracking:{kitState:t.waferTracking?.kitState||'Need System Wafer Kit',baseOverride:t.waferTracking?.baseOverride||'',additional:{shiny:Number(add.shiny||0),haze:Number(add.haze||0),dsw65:Number(add.dsw65||0),dsw65f:Number(add.dsw65f||0)}},
    history:Array.isArray(t.history)?t.history:[]
  }
}
function sampleState(){let families=['TARGA','BOXSTER','BOXSTER','BOXSTER','BOXSTER','BOXSTER','CELESTIQ','MACAN','PANAMERA','REGERA','REGERA','TARGA','TAYCAN','VANQUISH','ZEPHYR','BOXSTER','BOXSTER','BOXSTER','BOXSTER','BOXSTER'];let customers=['TSMC','KIOXIA','INTEL','SAMSUNG','MICRON','INFINEON','KIOXIA','MICRON','INFINEON','SONY','SAMSUNG','TSMC','PORSCHE','APPLE','MICRON'];let tools=families.map((f,i)=>normalizeTool({id:String(1350987+i),codename:f,model:i===0?'2955T':i%3===0?'2935I':'2915S2',customer:customers[i%customers.length],salesOrder:`SO-${String(i+1).padStart(2,'0')}`,driver:['Hao','Vinh','Daniel','Tony N','Allan','Hailey'][i%6],toolStatus:i<7?'Shipped':i<11?'Waiting FI':'FI',currentChecklist:i<7?'FI_200_90':i<11?'FI_130_010':i<15?'FI_150_010':'FI_160_010',shipDate:i===0?'2026-09-28':i<7?`2026-09-${String(22+i).padStart(2,'0')}`:`2026-10-${String((i-6)*2).padStart(2,'0')}`,fiHandoffDate:`2026-09-${String(10+i%12).padStart(2,'0')}`,leadProgress:i<7?100:(i*7)%65,originalQuarter:'CY26Q3',quarter:'CY26Q3',latestStatus:i===0?'Behind micro schedule · calibration NC open':'FI testing progressing'},i));return{version:VERSION,environment:'V8 PREVIEW',tools,actions:[{id:'a1',severity:'Critical',tool:'1350987',text:'Resolve calibration NC',owner:'Hao',due:'2026-09-26',status:'Open'},{id:'a2',severity:'High',tool:'1350995',text:'Confirm customer source',owner:'Daniel',due:'2026-09-27',status:'Open'},{id:'a3',severity:'Medium',tool:'1350999',text:'Check options arrival',owner:'Vinh',due:'2026-09-28',status:'Open'}],meetings:[],references:[],config:{plannedCount:20,quarterArchives:{}}}}
function loadState(){try{let v=JSON.parse(localStorage.getItem(V8KEY)||'null');if(v?.tools?.length)return normalizeState(v)}catch(e){}try{let v=JSON.parse(localStorage.getItem(V8PREVIEW)||'null');if(v?.tools?.length){let copy=normalizeState(v);copy.environment='V8.1 SANDBOX COPY OF V8/V7 DATA';localStorage.setItem(V8KEY,JSON.stringify(copy));return copy}}catch(e){}try{let v=JSON.parse(localStorage.getItem(V7PROD)||'null');if(v?.tools?.length){let copy=normalizeState(v);copy.environment='V8.1 SANDBOX COPY OF V7';localStorage.setItem(V8KEY,JSON.stringify(copy));return copy}}catch(e){}let st=sampleState();try{localStorage.setItem(V8KEY,JSON.stringify(st))}catch(e){}return st}
function normalizeState(s){return{...s,version:VERSION,tools:(s.tools||[]).map(normalizeTool),actions:s.actions||[],meetings:s.meetings||[],references:s.references||[],config:s.config||{}}}
function save(msg='SAVED'){try{localStorage.setItem(V8KEY,JSON.stringify(state))}catch(e){}toast(msg);render()}
function toolQuarter(t){return t.originalQuarter||t.quarter}
function isShipped(t){return t.toolStatus==='Shipped'||!!t.shippedAt}
function isArchived(t){return !!t.archivedAt}
function operationalTools(){let aq=activeQuarter();return state.tools.filter(t=>!isArchived(t)&&(toolQuarter(t)===aq||toolQuarter(t)<aq))}
function quarterTools(q){return state.tools.filter(t=>toolQuarter(t)===q&&!isArchived(t))}
function derive(t){let now=dateISO(),days=daysBetween(now,t.shipDate),cycle=t.fiHandoffDate?daysBetween(t.fiHandoffDate,isShipped(t)?(t.shippedAt?.slice(0,10)||t.shipDate||now):now):null;let progress=0;let m=/FI_(\d+)/.exec(t.currentChecklist||'');if(m)progress=Math.max(0,Math.min(100,(Number(m[1])-130)/.7));if(isShipped(t))progress=100;let behind=!isShipped(t)&&days!==null&&days<0;let attention=!isShipped(t)&&!behind&&days!==null&&days<=5;let carry=toolQuarter(t)<activeQuarter()&&!isArchived(t);return{days,cycle,progress:Math.round(progress),behind,attention,carry,status:isShipped(t)?'SHIPPED':behind?'BEHIND SCHEDULE':t.toolStatus==='Packing'?'PACKING':'ON SCHEDULE'}}
function photoFor(t){let c=(t.codename||'').toUpperCase();if(c==='REGERA'||c==='CELESTIQ')return'assets/tool-regera-celestiq.png';if(c==='ZEPHYR')return'assets/tool-zephyr.png';return'assets/tool-29xx-family.png'}
function countStatus(tools){let shipped=tools.filter(isShipped).length,packing=tools.filter(t=>t.toolStatus==='Packing').length,waiting=tools.filter(t=>/Waiting/i.test(t.toolStatus)).length,infi=Math.max(0,tools.length-shipped-packing-waiting);return{total:tools.length,shipped,packing,waiting,infi}}
function statusMessages(){let ops=operationalTools(),aq=activeQuarter(),qt=quarterTools(aq),c=countStatus(qt),oc=countStatus(ops),carry=ops.filter(t=>derive(t).carry&&!isShipped(t)),behind=ops.filter(t=>derive(t).behind),actions=(state.actions||[]).filter(a=>a.status!=='Complete');let qb=quarterBounds(aq),left=qb?daysBetween(dateISO(),dateISO(qb.end)):null;let msgs=[];if(carry.length)msgs.push({sev:'critical',title:'LEADS ALERT',sub:'CARRYOVER',text:`${carry.length} PRIOR-QUARTER CARRYOVER TOOL${carry.length===1?'':'S'} · SHIP ASAP`});else if(behind.length)msgs.push({sev:'critical',title:'LEADS ALERT',sub:'CRITICAL',text:`${behind.length} TOOL${behind.length===1?'':'S'} BEHIND SCHEDULE · ${actions.length} OPEN ACTIONS`});else msgs.push({sev:'good',title:'LEADS ALERT',sub:'CLEAR',text:`NO CRITICAL LEAD ESCALATIONS · ${actions.length} OPEN ACTIONS`});msgs.push({sev:left===0?'attention':'info',title:'SYSTEM STATUS',sub:left===0?'FINAL DAY':'LIVE FLEET',text:left===0?`${aq} FINAL DAY · ${c.total-c.shipped} TOOLS LEFT TO SHIP`:`${oc.waiting} WAITING FI · ${oc.infi} IN FI · ${oc.packing} PACKING · ${oc.shipped} SHIPPED`});msgs.push({sev:carry.length?'critical':left===0?'critical':'info',title:'COMMAND CENTER',sub:carry.length?'CARRYOVER':left===0?'FINAL DAY':'BRAIN',text:carry.length?`${aq} ACTIVE · ${carry.length} CARRYOVER · ${carry.map(t=>t.id).slice(0,3).join(' · ')}`:left===0?`${aq} QUARTER ENDS TODAY · ${c.shipped} OF ${c.total} SHIPPED`:`${aq} ACTIVE · ${c.shipped} OF ${c.total} SHIPPED · ${c.total-c.shipped} REMAINING`});return msgs}
function renderStatusBars(){let base=statusMessages(),rot=base.map((_,i)=>base[(i+statusIndex)%base.length]);$('#statusBars').innerHTML=rot.map((m,i)=>`<div class="status-bar ${m.sev} ${i===2?'command':''}"><div class="status-lamp"></div><div class="status-title">${m.title}<small>${m.sub}</small></div><div class="status-message">${esc(m.text)}</div><div class="status-open">OPEN →</div></div>`).join('')}
function renderHeader(){let aq=activeQuarter();$('#headerQuarter').textContent=aq;$('#footerQuarter').textContent=aq;$('#clockText').textContent=today().toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).toUpperCase();$('#modeText').textContent=state.environment||'V8 PREVIEW MODE';$('#connectionText').textContent='SANDBOX · V7 DATA SAFE';renderStatusBars();$('#mainNav').innerHTML=centers.map(([id,ic,n])=>`<button class="nav-btn ${route.center===id?'active':''}" data-center="${id}">${ic} &nbsp; ${n}</button>`).join('');renderSubNav()}
function renderSubNav(){let defs={operations:[['live','LIVE OPERATIONS'],['summary',`${activeQuarter()} SUMMARY`],['tools','TOOLS'],['daily','DAILY STATUS'],['quick','QUICK UPDATE']],shipping:[['home','SHIPPING CENTER']],priority:[['home','SYSTEM PRIORITIES']],status:[['home','DAILY STATUS']],cycle:[['home','CYCLE TIME']],meeting:[['home','MORNING MEETING']],action:[['home','ACTION CENTER']],reference:[['home','REFERENCE CENTER']],search:[['home','SEARCH CENTER']],archive:[['home','ARCHIVE CENTER']]};let arr=defs[route.center]||[];$('#subNav').innerHTML=arr.map(([id,n])=>`<button class="sub-btn ${route.sub===id?'active':''}" data-sub="${id}">${n}</button>`).join('')+`<span class="sub-spacer"></span><button class="action-btn" data-presentation="summary">▣ PRESENTATION</button><button class="action-btn" data-screenshot>SCREENSHOT</button>`}
function meter(p){return`<div class="meter"><i style="width:${Math.max(0,Math.min(100,p))}%"></i></div>`}
function quarterPulse(q){let tools=quarterTools(q),c=countStatus(tools),b=quarterBounds(q),left=b?Math.max(0,daysBetween(dateISO(),dateISO(b.end))):0;let fam=[...new Set(tools.map(t=>t.codename))];return`<section class="panel"><div class="panel-title">${q} QUARTER PULSE <small>LIVE</small></div><div class="quarter-pulse"><div class="kpi red"><h3>TOOLS LEFT TO SHIP</h3><strong>${c.total-c.shipped}</strong>${meter(c.total?c.shipped/c.total*100:0)}<small>${c.shipped} OF ${c.total} SHIPPED</small></div><div class="kpi yellow"><h3>${left===0?'FINAL DAY':'DAYS REMAINING'}</h3><strong>${left===0?'!':left}</strong>${meter(b?Math.max(0,Math.min(100,100-left/92*100)):0)}<small>${left===0?'QUARTER ENDS TODAY':q}</small></div></div><div class="family-bars">${fam.map(f=>{let a=tools.filter(t=>t.codename===f),s=a.filter(isShipped).length;return`<div class="family-row"><span>${esc(f)}</span><div class="bar"><i style="width:${a.length?s/a.length*100:0}%"></i></div><b>${s} / ${a.length}</b></div>`}).join('')}</div></section>`}
function fleetKpis(tools){let c=countStatus(tools);return`<div class="fleet-kpis"><div class="mini-kpi"><small>TOTAL</small><strong>${c.total}</strong></div><div class="mini-kpi"><small>PULLED IN</small><strong>0</strong></div><div class="mini-kpi"><small>PUSHED OUT</small><strong>0</strong></div><div class="mini-kpi"><small>UPDATED</small><strong>${c.total}</strong></div><div class="mini-kpi waiting"><small>WAITING FI</small><strong>${c.waiting}</strong></div><div class="mini-kpi infi"><small>IN FI</small><strong>${c.infi}</strong></div><div class="mini-kpi"><small>PACKING</small><strong>${c.packing}</strong></div><div class="mini-kpi shipped"><small>SHIPPED</small><strong>${c.shipped}</strong></div></div>`}
function miniTool(t,i){let d=derive(t);return`<div class="mini-tool ${d.behind?'behind':''}" data-tool="${esc(t.id)}"><img src="${photoFor(t)}"><b>#${i+1} ${esc(t.codename)}</b><small>${esc(t.model)} · ${esc(t.id)}</small><em>${d.status}${d.days!==null&&!isShipped(t)?` · ${Math.abs(d.days)} DAYS${d.days<0?' OVERDUE':''}`:''}</em></div>`}
function liveStatus(tools){let five=tools.slice(toolIndex,toolIndex+5);if(five.length<5)five=[...five,...tools.slice(0,5-five.length)];return`<section class="panel"><div class="panel-title">LIVE OPERATIONAL FLEET <small>${activeQuarter()} + CARRYOVER</small></div><div class="live-status">${fleetKpis(tools)}<div class="mini-tool-strip">${five.map(miniTool).join('')}</div></div></section>`}
function toolCard(t,i){let d=derive(t),cls=d.behind?'behind':d.attention?'attn':isShipped(t)?'shipped':'';let dayText=isShipped(t)?'SHIPPED':d.days===null?'NO DATE':d.days<0?`${Math.abs(d.days)} DAYS OVERDUE`:`${d.days} DAYS`;return`<article class="tool-card ${cls}" data-tool="${esc(t.id)}"><div class="tool-head"><div class="tool-priority">#${i+1}</div><b>${esc(t.codename)}</b><span>${d.status}</span></div><div class="tool-body"><img class="tool-photo" src="${photoFor(t)}"><div class="tool-metrics"><div class="metric"><small>SHIP COUNTDOWN</small><b>${dayText}</b></div><div class="metric"><small>FI PROGRESS</small><b>${d.progress}%</b></div><div class="metric"><small>MICRO SCHEDULE</small><b>${Math.min(100,d.progress+12)}%</b></div><div class="metric"><small>CYCLE TIME</small><b>${d.cycle??'—'} / 25</b></div><div class="metric"><small>PACKING</small><b>${isShipped(t)?'100':'0'}%</b></div></div></div><div class="tool-info"><div><span>UTID</span><b>${esc(t.id)}</b></div><div><span>MODEL</span><b>${esc(t.model)}</b></div><div><span>CUSTOMER</span><b>${esc(t.customer)}</b></div><div><span>SALES ORDER</span><b>${esc(t.salesOrder)}</b></div><div><span>DRIVER</span><b class="driver">${esc(t.driver)}</b></div>${d.carry?`<div style="display:block;background:#67101f;border:1px solid #ff315b;padding:5px;text-align:center;font-weight:900;color:#ff8ba1">⚠ QUARTER CARRYOVER · SHIP ASAP</div>`:''}<div><span>BADGES</span><div class="badge-preview">${Array.from({length:6},()=>'<i></i>').join('')}<b>+22</b></div></div></div><button class="tool-action" data-edit-tool="${esc(t.id)}">UPDATE TOOL STATUS →</button></article>`}
function operationsLive(){let tools=operationalTools();return`<div class="grid ops-top">${quarterPulse(activeQuarter())}${liveStatus(tools)}</div><section class="panel carousel-panel"><div class="panel-title"><span>TOOL CAROUSEL — ACTIVE FLEET</span><div class="carousel-toolbar"><button class="btn" data-carousel="prev">◀</button><button class="btn" data-carousel="next">▶</button><button class="btn" data-presentation="tools">▣ PRESENT</button></div></div><div class="tool-carousel">${tools.slice(toolIndex,toolIndex+5).concat(tools.slice(0,Math.max(0,5-tools.slice(toolIndex).length))).map(toolCard).join('')}</div></section>`}
function summaryComponent(q){let tools=quarterTools(q),c=countStatus(tools),b=quarterBounds(q),left=b?daysBetween(dateISO(),dateISO(b.end)):0,final=left===0,ended=left<0;let fam=[...new Set(tools.map(t=>t.codename))];let dayOf=b?Math.min(92,Math.max(1,daysBetween(dateISO(b.start),dateISO())+1)):0;return`<div class="summary-shell" data-summary-component="${q}"><div class="summary-hero"><div class="kpi red"><h3>${q} TOOLS LEFT TO SHIP</h3><strong>${Math.max(0,c.total-c.shipped)}</strong>${meter(c.total?c.shipped/c.total*100:0)}<small>${c.shipped} OF ${c.total} TOOLS SHIPPED &nbsp; | &nbsp; ${Math.max(0,c.total-c.shipped)} TOOLS LEFT</small></div><div class="kpi ${final||ended?'red':'yellow'}"><h3>${q} ${ended?'QUARTER ENDED':final?'LAST DAY OF THE QUARTER':'QUARTER COUNTDOWN'}</h3><strong>${ended?'ENDED':final?'FINAL DAY':Math.max(0,left)+' DAYS'}</strong>${meter(b?Math.max(0,Math.min(100,dayOf/92*100)):0)}<small>${ended?'FINAL CLOSE':`DAY ${dayOf} OF 92 &nbsp; | &nbsp; ${final?'QUARTER ENDS TODAY':left+' DAYS REMAINING'}`}</small></div></div>${fleetKpis(tools)}<div class="panel summary-family"><div class="summary-table"><div class="summary-cell">SYSTEM</div><div class="summary-cell">TOTAL</div><div class="summary-cell">WAITING FI</div><div class="summary-cell">IN FI</div><div class="summary-cell">PACKING</div><div class="summary-cell">SHIPPED</div><div class="summary-cell">SHIPPING PROGRESS</div><div class="summary-cell">REVEAL</div>${fam.map(f=>{let a=tools.filter(t=>t.codename===f),s=a.filter(isShipped).length,cc=countStatus(a);return`<div class="summary-cell name"><b>${esc(f)}</b><div class="tool-icons">${a.map(t=>`<span class="tool-icon ${isShipped(t)?'shipped':''}" data-tool="${esc(t.id)}"><img src="${photoFor(t)}"></span>`).join('')}</div></div><div class="summary-cell">${a.length}</div><div class="summary-cell waiting">${cc.waiting}</div><div class="summary-cell infi">${cc.infi}</div><div class="summary-cell packing">${cc.packing}</div><div class="summary-cell shipped">${cc.shipped}</div><div class="summary-cell progress-cell"><i style="width:${a.length?s/a.length*100:0}%"></i><span>${s} OF ${a.length} SHIPPED</span></div><div class="summary-cell reveal ${s===a.length?'open':''}">${s===a.length?'🎁':'🔒'}</div>`}).join('')}</div></div></div>`}
function dataTable(tools,kind='daily'){let rows=tools.map((t,i)=>{let d=derive(t);return`<tr data-tool="${esc(t.id)}"><td>${kind==='priority'?`<span class="priority-num">${i+1}</span>`:i+1}</td><td>${esc(t.id)}</td><td>${esc(t.codename)}</td><td>${esc(t.model)}</td><td>${esc(t.customer)}</td><td><span class="pill ${d.behind?'red':isShipped(t)?'green':d.attention?'yellow':'blue'}">${d.status}</span></td><td>${esc(t.currentChecklist)}</td><td>${fmtDate(t.shipDate)}</td><td>${d.days===null?'—':d.days}</td><td><button class="btn" data-edit-tool="${esc(t.id)}">OPEN</button></td></tr>`}).join('');return`<div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>UTID</th><th>TOOL TYPE</th><th>MODEL</th><th>CUSTOMER</th><th>STATUS</th><th>CURRENT STEP</th><th>SHIP DATE</th><th>DAYS</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`}
function toolsPage(){let tools=operationalTools();return`<section class="panel"><div class="panel-title">${activeQuarter()} TOOLS <small>${tools.length} ACTIVE / CARRYOVER</small></div><div class="tool-carousel" style="grid-template-columns:repeat(auto-fit,minmax(260px,1fr));overflow:visible">${tools.map(toolCard).join('')}</div></section>`}
function shippingPage(){let tools=operationalTools();return`<h1 class="page-title">SHIPPING CENTER — ${activeQuarter()}</h1><section class="panel data-panel"><div class="toolbar"><button class="btn primary">ALL</button><button class="btn">FI TESTING</button><button class="btn">PACKING</button><button class="btn">READY TO SHIP</button><button class="btn">SHIPPED</button></div>${dataTable(tools)}</section>`}
function priorityPage(){let tools=operationalTools().slice().sort((a,b)=>Number(derive(b).behind)-Number(derive(a).behind)||(derive(a).days??999)-(derive(b).days??999));return`<h1 class="page-title">SYSTEM PRIORITIES — ${activeQuarter()}</h1><section class="panel data-panel"><div class="toolbar"><button class="btn primary">ALL TOOLS</button><button class="btn">HIGHEST PRIORITY</button><button class="btn">BEHIND SCHEDULE</button><button class="btn">CRITICAL NCs</button><button class="btn">CUSTOMER SOURCE</button></div>${dataTable(tools,'priority')}</section>`}
function statusPage(){return`<h1 class="page-title">STATUS CENTER — DAILY STATUS</h1><section class="panel data-panel"><div class="toolbar"><button class="btn primary">DAILY STATUS</button><button class="btn">UPDATE COMMAND CENTER</button><span style="flex:1"></span><button class="btn">ALL TOOLS</button></div>${dataTable(operationalTools())}</section>`}
function cyclePage(){let tools=operationalTools();let vals=tools.map(t=>derive(t).cycle||0);return`<h1 class="page-title">CYCLE TIME CENTER</h1><div class="chart-grid"><section class="panel chart"><div class="panel-title">FI CYCLE TIME (DAYS)</div><div class="bars">${tools.slice(0,8).map((t,i)=>`<div class="bar-col"><i style="height:${Math.min(100,(vals[i]||8)/30*100)}%"></i><b>${esc(t.codename)}</b><small>${vals[i]||'—'}</small></div>`).join('')}</div></section><section class="panel chart"><div class="panel-title">CYCLE TIME TREND</div><div class="line-chart"><svg viewBox="0 0 500 180" preserveAspectRatio="none"><polyline fill="none" stroke="#12c9ff" stroke-width="4" points="0,130 60,110 120,120 180,75 240,90 300,55 360,70 420,45 500,60"/><polyline fill="none" stroke="#ff315b" stroke-width="3" points="0,105 60,100 120,92 180,95 240,80 300,84 360,68 420,75 500,48"/></svg></div></section></div><section class="panel data-panel" style="margin-top:10px">${dataTable(tools)}</section>`}
function meetingPage(){let tools=operationalTools().slice(0,7),actions=(state.actions||[]).filter(a=>a.status!=='Complete');return`<h1 class="page-title">MEETING CENTER — MORNING MEETING</h1><div class="meeting-grid"><section class="panel note-box"><h3>TODAY'S PRIORITIES</h3><ol>${tools.slice(0,5).map(t=>`<li><b>${esc(t.codename)}</b> — ${esc(derive(t).status)} · ${esc(t.currentChecklist)}</li>`).join('')}</ol></section><section class="panel note-box"><h3>MEETING NOTES</h3><ul><li>TARGA — confirm customer source requirements.</li><li>BOXSTER — calibration NC in progress.</li><li>CELESTIQ — packing handoff follow-up.</li><li>MACAN — waiting for CTD data.</li></ul><button class="btn primary">ADD NOTE</button></section><section class="panel note-box"><h3>ACTION ITEMS</h3>${actions.map(a=>`<div style="padding:7px;border-bottom:1px solid #123149"><b>${esc(a.tool)}</b> · ${esc(a.text)}<br><small>${esc(a.owner)} · ${fmtDate(a.due)}</small></div>`).join('')}<button class="btn primary" style="margin-top:10px">ADD ACTION</button></section></div>`}
function actionPage(){let acts=state.actions||[];return`<h1 class="page-title">ACTION CENTER</h1><section class="panel data-panel"><div class="toolbar"><button class="btn primary">OPEN ACTIONS</button><button class="btn">ALL ACTIONS</button><button class="btn">ESCALATIONS</button></div>${acts.map(a=>`<div class="action-card"><span class="pill ${a.severity==='Critical'?'red':a.severity==='High'?'yellow':'blue'}">${esc(a.severity)}</span><b>${esc(a.tool)}</b><span>${esc(a.text)}</span><span>${esc(a.owner)}</span></div>`).join('')}</section>`}
function referencePage(){let refs=[['📁','FILE MANAGER','Network & local files'],['🔗','QUICK LINKS','UTID lookup · SharePoint · Options'],['👥','DRIVER ROSTER','29 drivers'],['▦','TOOL TYPES','FI families'],['▣','TEMPLATES','NC forms · meeting templates'],['🛠','GUIDES','FI checklist guides']];return`<h1 class="page-title">REFERENCE CENTER</h1><div class="reference-grid">${refs.map(r=>`<section class="panel ref-card"><span>${r[0]}</span><strong>${r[1]}</strong><small>${r[2]}</small></section>`).join('')}</div>`}
function searchPage(){return`<h1 class="page-title">SEARCH CENTER</h1><section class="panel data-panel"><div class="toolbar"><input id="searchInput" placeholder="Search by UTID, model, customer, driver, status..."><button class="btn primary" data-run-search>SEARCH</button></div><div id="searchResults">${dataTable(operationalTools())}</div></section>`}
function archivePage(){let qs=[...new Set(state.tools.map(toolQuarter))].sort();return`<h1 class="page-title">ARCHIVE CENTER</h1><div class="archive-grid">${qs.map(q=>{let a=state.tools.filter(t=>toolQuarter(t)===q),s=a.filter(isShipped).length;return`<section class="panel archive-card"><small>${q} SUMMARY</small><h2>${s} OF ${a.length} SHIPPED</h2>${meter(a.length?s/a.length*100:0)}<p>${a.length?Math.round(s/a.length*100):0}% COMPLETION</p><button class="btn primary" data-summary-quarter="${q}">VIEW QUARTER SUMMARY</button></section>`}).join('')}</div>`}
function adminPage(){return`<h1 class="page-title">ADMINISTRATION CENTER — V8.1 FULL PREVIEW</h1><div class="notice"><b>SAFE FULL PREVIEW:</b> V8.1 includes the complete Tool Control Center and writes only to its own browser storage. Your V7 production data is not modified.</div><div class="admin-grid"><section class="panel admin-card"><h2>DATA</h2><p>Current sandbox: <b>${esc(state.environment)}</b></p><p>Tools loaded: <b>${state.tools.length}</b></p><button class="btn good" data-add-tool>+ ADD NEW TOOL</button> <button class="btn primary" data-import-v7>RE-IMPORT CURRENT V7 PRODUCTION DATA</button> <button class="btn danger" data-load-demo>LOAD V8 DEMO DATA</button></section><section class="panel admin-card"><h2>V8 FOUNDATION</h2><p>One application shell · one Tool Card · one Quarter Summary · full Tool Control Center · Quick Update · no V7 CSS loaded.</p><p>Browser zoom uses responsive layout instead of whole-app scaling.</p><button class="btn" data-presentation="summary">OPEN PRESENTATION MODE</button></section></div>`}
function quickUpdatePage(){let tools=operationalTools();return`<h1 class="page-title">UPDATED COMMAND CENTER — QUICK UPDATE</h1><section class="panel data-panel"><div class="toolbar"><span class="pill blue">MORNING + DAILY STATUS</span><span style="flex:1"></span><button class="btn primary" data-save-quick>SAVE ALL CHANGES</button></div><div class="table-wrap"><table class="data-table quick-table"><thead><tr><th>UTID</th><th>TOOL</th><th>FI STATUS</th><th>NEXT FI TASK</th><th>DRIVER</th><th>SHIP DATE</th><th>LATEST STATUS / NOTES</th></tr></thead><tbody>${tools.map(t=>`<tr data-quick-row="${esc(t.id)}"><td><b>${esc(t.id)}</b></td><td>${esc(t.codename)}</td><td><select data-q="toolStatus"><option ${t.toolStatus==='Waiting FI'?'selected':''}>Waiting FI</option><option ${t.toolStatus==='FI'?'selected':''}>FI</option><option ${t.toolStatus==='Packing'?'selected':''}>Packing</option><option ${t.toolStatus==='Shipped'?'selected':''}>Shipped</option></select></td><td><input data-q="currentChecklist" value="${esc(t.currentChecklist)}"></td><td><input data-q="driver" value="${esc(t.driver)}"></td><td><input type="date" data-q="shipDate" value="${esc(t.shipDate)}"></td><td><input data-q="latestStatus" value="${esc(t.latestStatus)}"></td></tr>`).join('')}</tbody></table></div></section>`}
function renderPage(){let html='';if(route.center==='operations'){if(route.sub==='summary')html=summaryComponent(activeQuarter());else if(route.sub==='tools')html=toolsPage();else if(route.sub==='daily')html=statusPage();else if(route.sub==='quick')html=quickUpdatePage();else html=operationsLive()}else if(route.center==='shipping')html=shippingPage();else if(route.center==='priority')html=priorityPage();else if(route.center==='status')html=statusPage();else if(route.center==='cycle')html=cyclePage();else if(route.center==='meeting')html=meetingPage();else if(route.center==='action')html=actionPage();else if(route.center==='reference')html=referencePage();else if(route.center==='search')html=searchPage();else if(route.center==='archive')html=archivePage();else if(route.center==='admin')html=adminPage();$('#workspace').innerHTML=html}
function render(){renderHeader();renderPage();if(presentation.open)renderPresentation()}
const editorTabs=[['overview','OVERVIEW'],['fi','FI PROGRESS'],['lead','LEAD / ADMIN'],['badges','28 BADGES'],['wafers','SYSTEM WAFERS'],['source','CUSTOMER SOURCE'],['str','STR'],['shipping','PACKING / SHIPPING'],['history','HISTORY'],['admin','ADMIN']];
function getPath(obj,path){return path.split('.').reduce((o,k)=>o?.[k],obj)}
function setPath(obj,path,val){let a=path.split('.'),o=obj;for(let i=0;i<a.length-1;i++)o=o[a[i]]??=(/^\d+$/.test(a[i+1])?[]:{});o[a[a.length-1]]=val}
function inputF(label,path,val,type='text',wide=''){return`<div class="field ${wide}"><label>${label}</label><input type="${type}" data-path="${path}" value="${esc(val??'')}"></div>`}
function selectF(label,path,val,opts,wide=''){return`<div class="field ${wide}"><label>${label}</label><select data-path="${path}">${opts.map(o=>`<option ${String(o)===String(val)?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`}
function areaF(label,path,val,wide='span3'){return`<div class="field ${wide}"><label>${label}</label><textarea data-path="${path}">${esc(val??'')}</textarea></div>`}
function checkF(label,path,val){return`<label class="check-field"><input type="checkbox" data-path="${path}" ${val?'checked':''}><span>${label}</span></label>`}
function editorSection(id,title,body){return`<section class="editor-section ${id==='overview'?'active':''}" data-editor-section="${id}"><div class="editor-section-title">${title}</div>${body}</section>`}
function openTool(id){let t=state.tools.find(x=>x.id===id);if(!t)return;let d=derive(t), extra=t.waferTracking.additional||{};
 let badges=Object.keys(t.badges||{}).map((n,i)=>`<div class="badge-edit ${t.badges[n]==='Complete'?'done':t.badges[n]==='N/A'?'na':''}"><b>${esc(n)}</b><select data-path="badges.${esc(n)}"><option ${t.badges[n]==='Required'?'selected':''}>Required</option><option ${t.badges[n]==='In Progress'?'selected':''}>In Progress</option><option ${t.badges[n]==='Complete'?'selected':''}>Complete</option><option ${t.badges[n]==='N/A'?'selected':''}>N/A</option></select></div>`).join('');
 let hist=(t.history||[]).slice().reverse().map(h=>`<div class="history-row"><b>${esc(h.when||'')}</b><span>${esc(h.what||'Update')}</span><small>${esc(h.detail||'')}</small></div>`).join('')||'<div class="empty-state">No V8 history recorded yet.</div>';
 let body=`<div class="tool-control-head"><div><small>TOOL CONTROL CENTER</small><h1>${esc(t.id)} · ${esc(t.codename)} · ${esc(t.model)}</h1><p><span class="pill ${d.behind?'red':isShipped(t)?'green':'blue'}">${d.status}</span>${d.carry?' <span class="pill red">QUARTER CARRYOVER · SHIP ASAP</span>':''}</p></div><div class="tool-control-kpis"><div><small>SHIP</small><b>${d.days===null?'TBD':d.days<0?`${Math.abs(d.days)}D OVER`:`${d.days}D`}</b></div><div><small>FI</small><b>${d.progress}%</b></div><div><small>CYCLE</small><b>${d.cycle??'—'}/${t.cycleTarget}</b></div></div></div>
 <div class="tool-control-layout"><aside class="editor-tabs">${editorTabs.map(([k,n],i)=>`<button data-editor-tab="${k}" class="${i===0?'active':''}">${n}<i>${k==='badges'?'28':k==='wafers'?(Object.values(extra).reduce((a,b)=>a+Number(b||0),0)||'') :''}</i></button>`).join('')}</aside><div class="editor-content">
 ${editorSection('overview','TOOL OVERVIEW',`<div class="edit-grid">${inputF('UTID','id',t.id)}${inputF('Tool Type','codename',t.codename)}${inputF('Model','model',t.model)}${inputF('Customer','customer',t.customer)}${inputF('Sales Order','salesOrder',t.salesOrder)}${inputF('Driver','driver',t.driver)}${inputF('Priority','priority',t.priority,'number')}${selectF('Quarter','originalQuarter',t.originalQuarter,['CY26Q3','CY26Q4','CY27Q1','CY27Q2'])}${selectF('Tool Status','toolStatus',t.toolStatus,['Waiting FI','FI','Packing','Shipped'])}${checkF('Reduced Process','reducedProcess',t.reducedProcess)}${areaF('Latest Status / Daily Update','latestStatus',t.latestStatus)}</div>`) }
 ${editorSection('fi','FI PROGRESS',`<div class="edit-grid">${inputF('Current FI Checklist','currentChecklist',t.currentChecklist)}${inputF('Current Lead Task','currentLeadTask',t.currentLeadTask)}${inputF('Current System Status','currentSystemStatus',t.currentSystemStatus)}${inputF('FI Handoff / Start','fiHandoffDate',t.fiHandoffDate,'date')}${inputF('Micro Schedule Target','microSchedule',t.microSchedule,'date')}${inputF('FI Forecast Date','nextForecastDate',t.nextForecastDate,'date')}${inputF('FI Forecast','fiForecast',t.fiForecast)}${inputF('Cycle Target Days','cycleTarget',t.cycleTarget,'number')}${inputF('Lead/Admin Progress %','leadProgress',t.leadProgress,'number')}${areaF('Next System Tasks (one per line)','nextSystemTasksText',(t.nextSystemTasks||[]).join('\n'))}${areaF('Lead Notes / Reminders','leadNotes',t.leadNotes)}</div>`) }
 ${editorSection('lead','LEAD / ADMIN TASKS',`<div class="edit-grid">${selectF('Options Request','requests.options',t.requests.options,['Need to Request','Requested','Received','N/A'])}${selectF('Lamp','requests.lamp',t.requests.lamp,['TBD','Required','Requested','Complete','N/A'])}${inputF('Special Wafers','requests.specialWafers',t.requests.specialWafers)}${selectF('Cal Chips','requests.calChips',t.requests.calChips,['Need to Request','Requested','Received','N/A'])}${inputF('Missing Options','requests.missingOptions',t.requests.missingOptions)}${selectF('MFG Options File','optionsFiles.manufacturing',t.optionsFiles.manufacturing,['TBD','Required','Complete','N/A'])}${selectF('Material Options File','optionsFiles.material',t.optionsFiles.material,['TBD','Required','Complete','N/A'])}${selectF('Impact Options File','optionsFiles.impact',t.optionsFiles.impact,['TBD','Required','Complete','N/A'])}${selectF('Install Options File','optionsFiles.install',t.optionsFiles.install,['TBD','Required','Complete','N/A'])}${selectF('RC Options File','optionsFiles.rc',t.optionsFiles.rc,['TBD','Required','Complete','N/A'])}${selectF('Customer Options File','optionsFiles.customer',t.optionsFiles.customer,['TBD','Required','Complete','N/A'])}</div>`) }
 ${editorSection('badges','OPERATIONAL BADGES — 28',`<div class="badge-editor-grid">${badges}</div>`) }
 ${editorSection('wafers','SYSTEM WAFER TRACKER',`<div class="wafer-layout"><div class="wafer-state">${selectF('Kit Workflow State','waferTracking.kitState',t.waferTracking.kitState,['Need System Wafer Kit','Need to Update System Wafer Log','Need to Notify Planners to Transact System Wafer Kit','System Wafer Kit Issued'],'span3')}${inputF('Base Kit Override / Exception','waferTracking.baseOverride',t.waferTracking.baseOverride)}</div><div class="wafer-counters">${[['shiny','SHINY'],['haze','HAZE'],['dsw65','DSW65'],['dsw65f','DSW65F']].map(([k,n])=>`<div class="counter"><small>ADDITIONAL ${n}</small><button data-wafer="${k}" data-delta="-1">−</button><b data-wafer-value="${k}">${Number(extra[k]||0)}</b><button data-wafer="${k}" data-delta="1">+</button><input type="number" min="0" data-path="waferTracking.additional.${k}" value="${Number(extra[k]||0)}"></div>`).join('')}</div><div class="base-kit"><b>BASE KIT REFERENCE</b><p>${['CELESTIQ','REGERA'].includes(t.codename.toUpperCase())?'1 Shiny · 1 Haze · 2 DSW65F':'1 Shiny · 1 Haze · 1 DSW65'}${t.codename.toUpperCase()==='TAYCAN'?' · Taycan exception may add 1 DSW65F':''}</p></div></div>`) }
 ${editorSection('source','CUSTOMER SOURCE',`<div class="edit-grid">${selectF('Customer Source Required','customerSource.required',t.customerSource.required,['TBD','Yes','No'])}${selectF('Pre-Source Checklist','customerSource.preSource',t.customerSource.preSource,['Not Started','In Progress','Complete','N/A'])}${selectF('CA Handoff','customerSource.caHandoff',t.customerSource.caHandoff,['Not Started','Ready','With CA','Returned to FI','Complete','N/A'])}${inputF('Customer Source Start','customerSource.sourceStart',t.customerSource.sourceStart,'date')}${inputF('Customer Source Complete','customerSource.sourceComplete',t.customerSource.sourceComplete,'date')}</div>`) }
 ${editorSection('str','STR WORKFLOW',`<div class="edit-grid">${selectF('STR Required','str.required',t.str.required,['TBD','Yes','No'])}${selectF('Requirements','str.requirements',t.str.requirements,['Not Received','Received','Reviewed','N/A'])}${selectF('FI STR Testing','str.testing',t.str.testing,['Not Started','In Progress','Complete','N/A'])}${inputF('STR Complete Date','str.complete',t.str.complete,'date')}</div>`) }
 ${editorSection('shipping','PACKING / SHIPPING',`<div class="edit-grid">${inputF('Manufacturing Ship Date','shipDate',t.shipDate,'date')}${selectF('Packing Schedule Status','shipping.scheduleStatus',t.shipping.scheduleStatus,['Not Started','Testing','Packing','Ready to Ship','Shipped'])}</div><div class="handoff-grid">${[['subsystems','SUBSYSTEMS'],['accessories','ACCESSORIES'],['cables','CABLES'],['mat','MAT'],['is','IS']].map(([k,n])=>checkF(n,`shipping.completed.${k}`,t.shipping.completed[k])).join('')}</div><div class="shipping-callout"><b>PACKING PROGRESS</b><span>${Object.values(t.shipping.completed).filter(Boolean).length} OF 5 HANDOFFS COMPLETE</span></div>`) }
 ${editorSection('history','TOOL HISTORY',`<div class="history-list">${hist}</div>`) }
 ${editorSection('admin','ADMINISTRATIVE CONTROLS',`<div class="admin-danger"><h3>TOOL LIFECYCLE</h3><p>Shipping and archiving are separate. Archive only after the tool no longer belongs in the operational fleet.</p><div class="edit-grid">${inputF('Archived At','archivedAt',t.archivedAt,'datetime-local')}${inputF('Shipped At','shippedAt',t.shippedAt,'datetime-local')}</div><div class="danger-actions"><button class="btn good" data-mark-shipped="${esc(t.id)}">MARK SHIPPED</button><button class="btn" data-archive-tool="${esc(t.id)}">ARCHIVE TOOL</button><button class="btn danger" data-delete-tool="${esc(t.id)}">DELETE TOOL</button></div></div>`) }
 </div></div><div class="editor-footer"><button class="btn" data-close-modal>CANCEL</button><span>V8.1 SANDBOX · V7 PRODUCTION DATA IS NOT MODIFIED</span><button class="btn primary" data-save-tool="${esc(t.id)}">SAVE TOOL</button></div>`;
 $('#modalBody').innerHTML=body;$('#modal').classList.add('tool-editor-modal');$('#modal').classList.remove('hidden')
}
function field(label,key,val,type='text'){return inputF(label,key,val,type)}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').classList.remove('tool-editor-modal')}
function renderPresentation(){let q=presentation.quarter||activeQuarter(),tools=operationalTools(),t=tools[presentation.toolIndex%Math.max(1,tools.length)];let content=presentation.type==='tools'&&t?`<div style="height:100%;padding:10px;display:grid;place-items:center"><div style="width:min(1500px,95vw)">${toolCard(t,presentation.toolIndex+1)}</div></div>`:summaryComponent(q);$('#presentation').innerHTML=`<div class="presentation-content">${content}</div><div class="presentation-nav"><button data-pres-tools class="${presentation.type==='tools'?'active':''}">${qLabel(activeQuarter())} TOOLS</button><button data-pres-summary="CY26Q3" class="${presentation.type==='summary'&&q==='CY26Q3'?'active':''}">CY26Q3 QUARTER SUMMARY</button><button data-pres-summary="CY26Q4" class="${presentation.type==='summary'&&q==='CY26Q4'?'active':''}">CY26Q4 QUARTER SUMMARY</button><button data-pres-prev>◀ PREVIOUS / NEXT ▶</button><button data-pres-exit>ESC TO EXIT</button></div>`;$('#presentation').classList.remove('hidden')}
function toast(s){let el=$('#toast');el.textContent=s;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function runSearch(){let q=($('#searchInput')?.value||'').trim().toLowerCase();let tools=state.tools.filter(t=>!q||Object.values(t).some(v=>typeof v==='string'&&v.toLowerCase().includes(q)));$('#searchResults').innerHTML=dataTable(tools)}
document.addEventListener('click',e=>{
 let b=e.target.closest('button,[data-tool],[data-summary-quarter]');if(!b)return;
 if(b.dataset.center){route={center:b.dataset.center,sub:b.dataset.center==='operations'?'live':'home'};render();return}
 if(b.dataset.sub){route.sub=b.dataset.sub;render();return}
 if(b.id==='adminBtn'){route={center:'admin',sub:'home'};render();return}
 if(b.dataset.tool){openTool(b.dataset.tool);return} if(b.dataset.editTool){openTool(b.dataset.editTool);return}
 if(b.dataset.editorTab){$$('.editor-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.editor-section').forEach(x=>x.classList.toggle('active',x.dataset.editorSection===b.dataset.editorTab));return}
 if(b.dataset.wafer){let inp=$(`#modal [data-path="waferTracking.additional.${b.dataset.wafer}"]`);if(inp){inp.value=Math.max(0,Number(inp.value||0)+Number(b.dataset.delta||0));let out=$(`#modal [data-wafer-value="${b.dataset.wafer}"]`);if(out)out.textContent=inp.value}return}
 if(b.hasAttribute('data-close-modal')){closeModal();return}
 if(b.dataset.saveTool){let t=state.tools.find(x=>x.id===b.dataset.saveTool);if(t){$$('#modal [data-path]').forEach(el=>{let val=el.type==='checkbox'?el.checked:el.value;if(el.type==='number')val=Number(val||0);setPath(t,el.dataset.path,val)});let nt=$('#modal [data-path="nextSystemTasksText"]');if(nt)t.nextSystemTasks=nt.value.split(/\n+/).map(x=>x.trim()).filter(Boolean);delete t.nextSystemTasksText;t.history=t.history||[];t.history.push({when:new Date().toLocaleString(),what:'Tool updated',detail:t.latestStatus||t.currentChecklist});save('TOOL UPDATED IN V8.1 SANDBOX');closeModal()}return}
 if(b.dataset.markShipped){let t=state.tools.find(x=>x.id===b.dataset.markShipped);if(t){t.toolStatus='Shipped';t.shippedAt=new Date().toISOString().slice(0,16);t.shipping.scheduleStatus='Shipped';t.history.push({when:new Date().toLocaleString(),what:'Marked shipped',detail:'Final cycle locked'});save('TOOL MARKED SHIPPED');openTool(t.id)}return}
 if(b.dataset.archiveTool){let t=state.tools.find(x=>x.id===b.dataset.archiveTool);if(t&&confirm(`Archive ${t.id}?`)){t.archivedAt=new Date().toISOString().slice(0,16);t.history.push({when:new Date().toLocaleString(),what:'Archived',detail:toolQuarter(t)});save('TOOL ARCHIVED');closeModal()}return}
 if(b.dataset.deleteTool){let t=state.tools.find(x=>x.id===b.dataset.deleteTool);if(t&&confirm(`Delete ${t.id} from the V8.1 SANDBOX only?`)){state.tools=state.tools.filter(x=>x!==t);save('TOOL DELETED FROM V8.1 SANDBOX');closeModal()}return}
 if(b.hasAttribute('data-save-quick')){$$('[data-quick-row]').forEach(row=>{let t=state.tools.find(x=>x.id===row.dataset.quickRow);if(t)row.querySelectorAll('[data-q]').forEach(el=>t[el.dataset.q]=el.value)});save('QUICK UPDATE SAVED');return}
 if(b.dataset.carousel){let tools=operationalTools();toolIndex=(toolIndex+(b.dataset.carousel==='next'?5:-5)+Math.max(1,tools.length))%Math.max(1,tools.length);render();return}
 if(b.dataset.presentation){presentation={open:true,type:b.dataset.presentation,quarter:activeQuarter(),toolIndex:0};renderPresentation();return}
 if(b.dataset.presSummary){presentation.type='summary';presentation.quarter=b.dataset.presSummary;renderPresentation();return}
 if(b.hasAttribute('data-pres-tools')){presentation.type='tools';renderPresentation();return}
 if(b.hasAttribute('data-pres-prev')){if(presentation.type==='tools')presentation.toolIndex=(presentation.toolIndex+1)%Math.max(1,operationalTools().length);else presentation.quarter=presentation.quarter==='CY26Q3'?'CY26Q4':'CY26Q3';renderPresentation();return}
 if(b.hasAttribute('data-pres-exit')){presentation.open=false;$('#presentation').classList.add('hidden');return}
 if(b.dataset.summaryQuarter){route={center:'operations',sub:'summary'};render();return}
 if(b.hasAttribute('data-run-search')){runSearch();return}
 if(b.hasAttribute('data-add-tool')){let id=`NEW-${Date.now().toString().slice(-6)}`;let t=normalizeTool({id,codename:'BOXSTER',model:'2915S2',originalQuarter:activeQuarter(),quarter:activeQuarter(),customer:'NO CUSTOMER',salesOrder:'NO SALES ORDER',driver:'UNASSIGNED',toolStatus:'Waiting FI',priority:state.tools.length+1},state.tools.length);state.tools.push(t);save('NEW TOOL ADDED TO V8.1 SANDBOX');openTool(t.id);return}
 if(b.hasAttribute('data-import-v7')){try{let v=JSON.parse(localStorage.getItem(V7PROD)||'null');if(!v?.tools?.length)return alert('No V7 production data was found in this browser.');state=normalizeState(v);state.environment='V8.1 SANDBOX COPY OF V7';localStorage.setItem(V8KEY,JSON.stringify(state));toast('V7 DATA COPIED INTO V8.1 SANDBOX');render()}catch(err){alert(err.message)}return}
 if(b.hasAttribute('data-load-demo')){if(confirm('Replace only the V8.1 sandbox with demo data? V7 will not be changed.')){state=sampleState();state.environment='V8.1 FULL DEMO';save('V8.1 DEMO DATA LOADED')}return}
 if(b.hasAttribute('data-screenshot')){document.documentElement.requestFullscreen?.();return}
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&presentation.open){presentation.open=false;$('#presentation').classList.add('hidden')}if(e.key==='Escape'&&!$('#modal').classList.contains('hidden'))closeModal()});
setInterval(()=>{statusIndex=(statusIndex+1)%3;renderStatusBars()},8000);setInterval(()=>{let c=$('#clockText');if(c)c.textContent=today().toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).toUpperCase()},30000);
render();
})();
